(defpackage #:pine/data
  (:use #:cl)
  (:shadow #:map #:set)
  (:export
   #:map #:seq #:set #:mapp #:seqp
   #:setp #:collectionp #:lookup #:with #:without
   #:size #:keys #:vals #:pairs #:do-each
   #:do-pairs #:do-map #:as #:merged #:contains
   #:no-map
   #:no-seq #:no-set #:capped
   #:cas-p #:emptied
   #:same))
(in-package #:pine/data)

(defvar +no-map+ (fset:empty-map))
(defvar +no-seq+ (fset:empty-seq))
(defvar +no-set+ (fset:empty-set))

(defun no-map () +no-map+)
(defun no-seq () +no-seq+)
(defun no-set () +no-set+)

(defun map (&rest pairs)
  (loop :with out := +no-map+
        :for (key value) :on pairs :by #'cddr
        :do (setf out (fset:with out key value))
        :finally (return out)))

(defun seq (&rest values) (fset:convert 'fset:seq values))

(defun set (&rest values) (fset:convert 'fset:set values))

(defun mapp (x) (fset:map? x))
(defun seqp (x) (fset:seq? x))
(defun setp (x) (fset:set? x))
(defun collectionp (x) (or (mapp x) (seqp x) (setp x)))

(defgeneric lookup (collection key &optional default)
  (:method ((c fset:map) key &optional default)
    (multiple-value-bind (value foundp) (fset:lookup c key)
      (if foundp (values value t) (values default nil))))
  (:method ((c fset:seq) key &optional default)
    (if (and (integerp key) (>= key 0) (< key (fset:size c)))
        (values (fset:@ c key) t)
        (values default nil)))
  (:method ((c fset:set) key &optional default)
    (if (fset:contains? c key) (values key t) (values default nil)))
  (:method ((c null) key &optional default)
    (declare (ignore key))
    (values default nil))
  (:method ((c hash-table) key &optional default)
    (multiple-value-bind (value foundp) (gethash key c default)
      (values value foundp)))
  (:method ((c cons) key &optional default)
    (if (integerp key)
        (let ((tail (and (>= key 0) (nthcdr key c))))
          (if tail (values (car tail) t) (values default nil)))
        (let ((tail (loop :for rest :on c :by #'cddr
                          :when (eql (car rest) key) :do (return rest))))
          (if tail (values (second tail) t) (values default nil))))))

(defgeneric with (collection key &optional value)
  (:method ((c fset:map) key &optional value) (fset:with c key value))
  (:method ((c fset:seq) key &optional (value nil valuep))
    (if valuep (fset:with c key value) (fset:with-last c key)))
  (:method ((c fset:set) key &optional value)
    (declare (ignore value))
    (fset:with c key))
  (:method ((c null) key &optional (value nil valuep))
    (if valuep (fset:with +no-map+ key value) (fset:with-last +no-seq+ key)))
  (:method ((c cons) key &optional value)
    (declare (ignore key value))
    (error "~s is a list; WITH builds the kinds that share what they keep." c)))

(defgeneric without (collection key)
  (:method ((c fset:map) key) (fset:less c key))
  (:method ((c fset:seq) key) (fset:less c key))
  (:method ((c fset:set) key) (fset:less c key))
  (:method ((c null) key) (declare (ignore key)) nil)
  (:method ((c cons) key)
    (declare (ignore key))
    (error "~s is a list; WITHOUT builds the kinds that share what they keep." c)))

(defgeneric size (collection)
  (:method ((c fset:collection)) (fset:size c))
  (:method ((c null)) 0)
  (:method ((c sequence)) (length c))
  (:method ((c hash-table)) (hash-table-count c)))

(defgeneric contains (collection value)
  (:method ((c fset:set) value) (fset:contains? c value))
  (:method ((c fset:seq) value) (and (fset:position value c) t))
  (:method ((c fset:map) value) (nth-value 1 (fset:lookup c value)))
  (:method ((c null) value) (declare (ignore value)) nil)
  (:method ((c cons) value) (and (cl:member value c :test #'fset:equal?) t))
  (:method ((c hash-table) value) (nth-value 1 (gethash value c))))

(defgeneric keys (collection)
  (:method ((c fset:map)) (fset:convert 'list (fset:domain c)))
  (:method ((c fset:set)) (fset:convert 'list c))
  (:method ((c fset:seq)) (loop :for i :below (fset:size c) :collect i))
  (:method ((c null)) nil)
  (:method ((c cons)) (loop :for i :below (length c) :collect i))
  (:method ((c hash-table))
    (loop :for k :being :the :hash-keys :of c :collect k)))

(defgeneric vals (collection)
  (:method ((c fset:map)) (fset:convert 'list (fset:range c)))
  (:method ((c fset:seq)) (fset:convert 'list c))
  (:method ((c fset:set)) (fset:convert 'list c))
  (:method ((c null)) nil)
  (:method ((c cons)) (copy-list c))
  (:method ((c hash-table))
    (loop :for v :being :the :hash-values :of c :collect v)))

(defun pairs (collection)
  (loop :for key :in (keys collection) :collect (cons key (lookup collection key))))

(defmacro do-map ((key value collection &optional result) &body body)
  (let ((c (gensym)) (k (gensym)) (v (gensym)))
    `(let ((,c ,collection))
       (cond ((mapp ,c)
              (fset:do-map (,k ,v ,c)
                (let ((,key ,k) (,value ,v))
                  (declare (ignorable ,key ,value))
                  ,@body)))
             ((null ,c))
             (t (error "~s is not a map to walk." ,c)))
       ,result)))

(defmacro do-pairs ((key value collection &optional result) &body body)
  (let ((c (gensym)) (k (gensym)) (v (gensym)) (i (gensym)))
    `(let ((,c ,collection))
       (cond ((mapp ,c) (fset:do-map (,k ,v ,c)
                          (let ((,key ,k) (,value ,v))
                            (declare (ignorable ,key ,value))
                            ,@body))
                        ,result)
             ((seqp ,c) (let ((,i -1))
                          (fset:do-seq (,v ,c)
                            (incf ,i)
                            (let ((,key ,i) (,value ,v))
                              (declare (ignorable ,key ,value))
                              ,@body))
                          ,result))
             ((setp ,c) (fset:do-set (,v ,c)
                          (let ((,key ,v) (,value ,v))
                            (declare (ignorable ,key ,value))
                            ,@body))
                        ,result)
             ((null ,c) ,result)
             (t (error "~s is not something to walk in pairs." ,c))))))

(defmacro do-each ((value collection &optional result) &body body)
  (let ((c (gensym)) (k (gensym)) (v (gensym)))
    (flet ((each () `(let ((,value ,v))
                       (declare (ignorable ,value))
                       ,@body)))
      `(let ((,c ,collection))
         (cond ((mapp ,c) (fset:do-map (,k ,v ,c) (declare (ignorable ,k)) ,(each)))
               ((seqp ,c) (fset:do-seq (,v ,c) ,(each)))
               ((setp ,c) (fset:do-set (,v ,c) ,(each)))
               ((listp ,c) (dolist (,v ,c) ,(each)))
               ((hash-table-p ,c)
                (maphash (lambda (,k ,v) (declare (ignorable ,k)) ,(each)) ,c))
               (t (error "~s is not something to walk." ,c)))
         ,result))))

(defgeneric as (kind collection)
  (:method ((kind (eql :list)) collection)
    (if (collectionp collection) (fset:convert 'list collection) collection))
  (:method ((kind (eql :seq)) collection) (fset:convert 'fset:seq collection))
  (:method ((kind (eql :set)) collection) (fset:convert 'fset:set collection))
  (:method ((kind (eql :map)) collection) (fset:convert 'fset:map collection))
  (:method ((kind (eql :vector)) collection) (fset:convert 'vector collection)))

(defun same (a b)
  (fset:equal? a b))

(defun merged (&rest collections)
  (reduce (lambda (a b)
            (cond ((null b) a)
                  ((and (mapp a) (mapp b)) (fset:map-union a b))
                  (t (error "~s and ~s are not both maps." a b))))
          collections :initial-value +no-map+))

(defun capped (list value n)
  (let ((next (cons value list)))
    (if (nthcdr n next) (cl:subseq next 0 n) next)))

(defmacro emptied (place &environment env)
  (multiple-value-bind (temps values old new cas-form read-form)
      (sb-ext:get-cas-expansion place env)
    `(let* (,@(mapcar #'list temps values)
            (,new nil))
       (loop :for ,old := ,read-form
             :until (eq ,old ,cas-form)
             :finally (return ,old)))))

(defmacro cas-p (place old new &environment env)
  (multiple-value-bind (temps values old-var new-var cas-form read-form)
      (sb-ext:get-cas-expansion place env)
    (declare (ignore read-form))
    `(let* (,@(mapcar #'list temps values)
            (,old-var ,old)
            (,new-var ,new))
       (eq ,old-var ,cas-form))))

