;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package :pine/vt)

(declaim (optimize (speed 3) (safety 1)))

(defun face-attrs-to-plist (face)
  (when face
    (let ((props nil))
      (when (face-bold face)
        (push t props) (push :bold props))
      (when (face-faint face)
        (push t props) (push :faint props))
      (when (face-italic face)
        (push t props) (push :italic props))
      (when (face-underline face)
        (push t props) (push :underline props))
      (when (face-crossed face)
        (push t props) (push :strike-through props))
      (when (face-inverse face)
        (push t props) (push :inverse props))
      (let ((fg (resolve-color (face-fg face)))
            (bg (resolve-color (face-bg face))))
        (when (face-inverse face)
          (rotatef fg bg))
        (when (face-conceal face)
          (setf fg bg))
        (when fg (push fg props) (push :fg props))
        (when bg (push bg props) (push :bg props)))
      props)))

(defun resolve-color (color)
  (cond
    ((null color) nil)
    ((integerp color) color)
    ((and (listp color) (= (length color) 3))
     color)
    (t nil)))

(defun term-render-line (term y &optional (chars (make-string (term-width term)
                                                              :initial-element #\Space)))
  (let* ((w (term-width term))
         (row (aref (term-grid term) y))
         (font-changes nil)
         (prev-face nil))
    (dotimes (x w)
      (let* ((cell (aref row x))
             (ch (cell-char cell))
             (face (cell-face cell)))
        (setf (schar chars x) (if (graphic-char-p ch) ch #\Space))
        (unless (face-attrs-equal face prev-face)
          (push (list x (face-attrs-to-plist face)) font-changes)
          (setf prev-face face))))
    (values chars (nreverse font-changes))))

(defun term-dump-to-string (term)
  (with-output-to-string (s)
    (dotimes (y (term-height term))
      (let ((row (aref (term-grid term) y)))
        (dotimes (x (term-width term))
          (write-char (cell-char (aref row x)) s)))
      (unless (= y (1- (term-height term)))
        (terpri s)))))

(defun term-dump-row-string (term y)
  (let* ((w (term-width term))
         (row (aref (term-grid term) y))
         (s (make-string w)))
    (dotimes (x w s)
      (setf (schar s x) (cell-char (aref row x))))))

(defun write-color-code (color base s)
  (cond
    ((and (integerp color) (<= 0 color 7))
     (format s "~D" (+ base color)))
    ((and (integerp color) (<= 8 color 15))
     (format s "~D" (+ (if (= base 38) 90 100) (- color 8))))
    ((and (integerp color) (<= 0 color 255))
     (format s "~D;5;~D" base color))
    ((and (listp color) (= (length color) 3))
     (format s "~D;2;~D;~D;~D" base
             (first color) (second color) (third color)))
    (t (format s "~D" (+ base 9)))))

(defun write-sgr (face s)
  "Write FACE's SGR escape sequence directly to stream S, no intermediates."
  (write-char #\Escape s)
  (write-char #\[ s)
  (if (null face)
      (write-char #\0 s)
      (let ((any nil))
        (flet ((sep () (if any (write-char #\; s) (setf any t))))
          (when (face-bold face) (sep) (write-char #\1 s))
          (when (face-faint face) (sep) (write-char #\2 s))
          (when (face-italic face) (sep) (write-char #\3 s))
          (when (face-underline face) (sep) (write-char #\4 s))
          (when (face-inverse face) (sep) (write-char #\7 s))
          (when (face-crossed face) (sep) (write-char #\9 s))
          (let ((fg (if (face-inverse face) (face-bg face) (face-fg face)))
                (bg (if (face-inverse face) (face-fg face) (face-bg face))))
            (when (face-conceal face)
              (setf fg bg))
            (when fg (sep) (write-color-code fg 38 s))
            (when bg (sep) (write-color-code bg 48 s))))
        (unless any (write-char #\0 s))))
  (write-char #\m s))

(defun term-render-ansi-line (term y)
  (let* ((w (term-width term))
         (row (aref (term-grid term) y))
         (prev-face nil))
    (with-output-to-string (s)
      (dotimes (x w)
        (let* ((cell (aref row x))
               (ch (cell-char cell))
               (face (cell-face cell)))
          (unless (face-attrs-equal face prev-face)
            (write-sgr face s)
            (setf prev-face face))
          (write-char (if (graphic-char-p ch) ch #\Space) s)))
      (write-sgr nil s))))
