(in-package :pine.test)

(def-suite :pine.editor.commands :in :pine)
(in-suite :pine.editor.commands)

;;;; Live integration over a real server and buffer actors. The substrate is
;;;; built once; the tests run in dependency order and carry state forward,
;;;; the way an editor session does.

(defvar *client* nil)
(defvar *server* nil)

(defun ensure-editor-env ()
  (unless *client*
    (%fresh-store "/tmp/pine-editor-test-store.db")
    (let ((srv (pine.core.server:start-server)))
      (setf pine.core.server:*server* srv
            *server* srv
            (pine.core.server:ts-runtime srv) (pine.ts.runtime:make-ts-runtime))
      (pine.core.event:make-event-bus srv)
      (pine.core.actor:start-agent-registry srv)
      (pine.core.actor:start-local-agent srv)
      (pine.text.buffer:start-buffer-registry srv)
      ;; the world gate stays off for the suite -- tree tests assert seeded
      ;; shapes; the world-save test flips it on around itself.
      (setf (pine.state.var:var :world-save) nil)
      (let ((client (pine.editor.frame::start-client srv)))
        (setf pine.editor.frame::*client* client
              *client* client)
        (pine.ui.render:start-renderer client)
        (setf (pine.editor.frame::paint-sink client)
              (lambda (&rest _) (declare (ignore _)) nil))
        (let ((buf (pine.editor.frame::make-buffer "scratch")))
          (pine.editor.frame::make-window buf "scratch"
                                   :row 0 :col 0 :width 80 :height 29 :focused t)
          (setf (pine.editor.frame::current-buffer client) buf)
          (pine.editor.frame::set-buffer-mode buf :text-mode))
        (pine.editor.minibuffer:ensure-minibuffer client)
        (sleep 0.2)))))

(defun key (s)
  (pine.editor.command::dispatch *client* (pine.editor.key::parse-key s))
  (sleep 0.06))

(defun mbtext ()
  (sento.actor:ask-s (pine.editor.frame::minibuffer-buffer *client*) '(:get-text) :time-out 5))

(defun mbcol ()
  (pine.text.buffer:point-col
   (sento.actor:ask-s (pine.editor.frame::minibuffer-buffer *client*)
                      '(:get-snapshot) :time-out 5)))

(defun btext (buf)
  (sento.actor:ask-s buf '(:get-text) :time-out 5))

(test minibuffer-editing
  "The minibuffer is a real buffer: editing commands work on the input, the
popup renders and styles, Return accepts the candidate."
  (ensure-editor-env)
  (let ((chosen :none))
    (pine.editor.minibuffer:completing-read "M-x " '("forward-word" "backward-word" "kill-line")
      (lambda (r) (setf chosen r)))
    (sleep 0.15)
    (is (eq (pine.editor.frame::current-buffer *client*)
            (pine.editor.frame::minibuffer-buffer *client*)))
    (key "a") (key "b") (key "c")
    (is (string= "abc" (mbtext)))
    (key "C-a") (key "C-f") (key "X")
    (is (string= "aXbc" (mbtext)))
    (is (= 2 (mbcol)))
    (key "C-e") (key "BackSpace")
    (is (string= "aXb" (mbtext)))
    (key "C-a") (key "C-k")
    (is (string= "" (mbtext)))
    (dolist (ch '("f" "o" "r" "w" "a" "r" "d")) (key ch))
    (sleep 0.15)
    (is (equal '("forward-word")
               (mapcar #'pine.editor.completion:candidate-string
                       (pine.editor.frame::filtered (pine.editor.minibuffer:completion)))))
    (let ((rows (pine.editor.frame::popup-rows (pine.editor.minibuffer:completion))))
      (is (not (null rows)))
      (is (search "forward-word" (car (first rows))))
      (is (equal (multiple-value-bind (r g b)
                     (pine.ui.face:hex-rgb (pine.ui.face:color :bg-active))
                   (list r g b))
                 (subseq (rest (first (cdr (first rows)))) 3 6))))
    (key "Return") (sleep 0.15)
    (is (string= "forward-word" chosen))
    (is (not (eq (pine.editor.frame::current-buffer *client*)
                 (pine.editor.frame::minibuffer-buffer *client*))))))

(test (nested-prompt :depends-on minibuffer-editing)
  "A prompt fired while one is active replaces it without wedging: the return
buffer stays the original, abort restores it, typing lands in it."
  (let ((file-buf (pine.editor.frame::current-buffer *client*)))
    (pine.editor.minibuffer:completing-read "M-x " '("one" "two") (lambda (r) r))
    (sleep 0.1)
    (pine.editor.minibuffer:completing-read "M-x " '("three") (lambda (r) r))
    (sleep 0.1)
    (is (eq file-buf (pine.editor.frame::saved-buffer *client*)))
    (pine.editor.minibuffer:minibuffer-abort) (sleep 0.1)
    (is (eq file-buf (pine.editor.frame::current-buffer *client*)))
    (key "q") (sleep 0.15)
    (is (search "q" (btext file-buf)))
    (key "BackSpace") (sleep 0.1)))

(test (prompt-abort :depends-on nested-prompt)
  "C-g aborts a prompt: no callback, buffer restored, popup cleared."
  (let ((chosen :none))
    (pine.editor.minibuffer:completing-read "M-x " '("aaa" "bbb") (lambda (r) (setf chosen r)))
    (sleep 0.1) (key "a")
    (key "C-g") (sleep 0.1)
    (is (eq :none chosen))
    (is (not (eq (pine.editor.frame::current-buffer *client*)
                 (pine.editor.frame::minibuffer-buffer *client*))))
    (is (null (pine.editor.frame::popup-rows (pine.editor.minibuffer:completion))))
    (is (null (find-symbol "COMPLETIONS-TEXT" :pine.editor.echo)))))

(test (error-trapping :depends-on prompt-abort)
  "A failing edit surfaces through the debugger with RETRY; the buffer keeps
its prior state and recovers. A failing command routes by :debug-on-error."
  (let ((buf (pine.editor.frame::make-buffer "err-scratch")) (saw nil) (saw2 nil))
    (pine.editor.frame::set-buffer-mode buf :text-mode)
    (sento.actor:tell buf (list :insert :text "hello"))
    (sleep 0.1)
    (setf pine.core.eval:*on-debug*
          (lambda (ev) (setf saw ev) (pine.core.eval:pick-restart ev "ABORT")))
    (sento.actor:tell buf (list :insert :text 42))
    (sleep 0.25)
    (is (not (null saw)))
    (is (eq :error (and saw (pine.core.eval:evaluation-status saw))))
    (is (string= "hello" (btext buf)))
    (is (member "RETRY" (mapcar #'first (pine.core.eval:evaluation-restarts saw))
                :test #'string=))
    (sento.actor:tell buf (list :insert :text "!"))
    (sleep 0.15)
    (let ((tx (btext buf)))
      (is (and (= 6 (length tx)) (search "hello" tx))))
    (pine.editor.command::define-command "probe-boom" () (error "boom"))
    (setf pine.core.eval:*on-debug* (lambda (ev) (setf saw2 ev)))
    (setf (pine.state.var:var :debug-on-error) t)
    (pine.editor.command::call-command "probe-boom")
    (is (not (null saw2)))
    (setf saw2 nil)
    (setf (pine.state.var:var :debug-on-error) nil)
    (pine.editor.command::call-command "probe-boom")
    (is (null saw2))
    (setf pine.core.eval:*on-debug* nil)))

(test (debugger-sessions :depends-on error-trapping)
  "Concurrent faults coexist in the session registry; Tab pages; restart-row
activation resolves and advances; the eval target follows the fault."
  (setf pine.editor.debugger:*debugger-sessions* nil pine.editor.debugger:*attended-session* nil)
  (pine.editor.debugger:%agent-debug-surface
   (list :agent-debug :agent "alpha" :eval-id 1 :condition "boom-a"
         :restarts (list "RETRY" "ABORT")))
  (pine.editor.debugger:%agent-debug-surface
   (list :agent-debug :agent "beta" :eval-id 2 :condition "boom-b"
         :restarts (list "ABORT")))
  (sleep 0.1)
  (is (= 2 (length pine.editor.debugger:*debugger-sessions*)))
  (is (string= "beta" (pine.editor.debugger::dbg-session-agent pine.editor.debugger:*attended-session*)))
  (is (equal "beta" pine.editor.target:*eval-target*))
  (let ((txt (btext (pine.editor.frame::buffer "*debugger*"))))
    (is (search "alpha" txt))
    (is (search "beta" txt))
    (is (search "[ABORT]" txt)))
  (pine.editor.command::call-command "debugger-next-session") (sleep 0.05)
  (is (string= "alpha" (pine.editor.debugger::dbg-session-agent pine.editor.debugger:*attended-session*)))
  (is (equal "alpha" pine.editor.target:*eval-target*))
  (pine.editor.command::call-command "layout-next") (sleep 0.1)
  (pine.editor.command::call-command "layout-activate") (sleep 0.05)
  (is (= 1 (length pine.editor.debugger:*debugger-sessions*)))
  (is (string= "beta" (pine.editor.debugger::dbg-session-agent pine.editor.debugger:*attended-session*)))
  (pine.editor.debugger:invoke-pending-restart "ABORT") (sleep 0.05)
  (is (= 0 (length pine.editor.debugger:*debugger-sessions*)))
  (is (null pine.editor.debugger:*attended-session*))
  (is (eq :local pine.editor.target:*eval-target*)))

(test (one-eval-path :depends-on debugger-sessions)
  "eval-in-target :local runs through the one eval path."
  (let ((done :none))
    (pine.editor.target:eval-in-target "(+ 1 2)" (find-package :cl-user)
      :on-done (lambda (ev) (setf done (first (pine.core.eval:evaluation-values ev)))))
    (sleep 0.3)
    (is (eql 3 done))))

(test (jobs-buffer :depends-on one-eval-path)
  "The jobs layout buffer lists the local evaluations."
  (pine.editor.command::call-command "jobs") (sleep 0.15)
  (let ((txt (btext (pine.editor.frame::buffer "*jobs*"))))
    (is (search "Jobs" txt))
    (is (search "local" txt))))

(test (layout-render :depends-on jobs-buffer)
  "pine.ui.cells:render: row texts, face and css styling, node-at."
  (multiple-value-bind (rows root)
      (pine.ui.cells:render
       (pine.ui.build:column :align :stretch
         (pine.ui.build:label "head" :face :keyword)
         (pine.ui.build:choice (pine.ui.build:label "aaa"))
         (pine.ui.build:choice (pine.ui.build:label "bbb")))
       10 :selection 1)
    (is (equal '("head" "  aaa" "> bbb")
               (mapcar (lambda (r) (string-right-trim " " (car r))) rows)))
    (is (equal (pine.ui.face:face-fg :keyword)
               (subseq (rest (first (cdr (first rows)))) 0 3)))
    (let ((hit (pine.ui.layout:node-at root 2 3)))
      (is (and hit (typep hit 'pine.ui.node:selectable)
               (pine.ui.node:selectedp hit)))))
  (multiple-value-bind (rows root)
      (pine.ui.cells:render (pine.ui.build:label "x" :class "nm-title") 6)
    (declare (ignore root))
    (let ((run (rest (first (cdr (first rows))))))
      (is (equal (multiple-value-bind (r g b)
                     (pine.ui.face:hex-rgb (pine.ui.face:color :fg))
                   (list (list r g b) 1))
                 (list (subseq run 0 3) (nth 6 run)))))))

(test (layout-buffers :depends-on layout-render)
  "Layout buffers: set-layout renders rows, selection follows, activation
fires, reproject takes a new width."
  (let ((fired nil)
        (buf (pine.editor.frame::make-buffer "layout-probe")))
    (sento.actor:tell buf
      (list :set-layout :width 12 :builder
            (lambda (state) (declare (ignore state))
              (pine.ui.build:column :align :stretch
                (pine.ui.build:label "hd" :face :keyword)
                (pine.ui.build:choice :data (lambda () (setf fired :one))
                  (pine.ui.build:label "one"))
                (pine.ui.build:choice :data (lambda () (setf fired :two))
                  (pine.ui.build:label "two"))))))
    (sleep 0.15)
    (is (string= (format nil "hd~%> one~%  two") (btext buf)))
    (setf (pine.editor.frame::current-buffer *client*) buf)
    (pine.editor.command::call-command "layout-next") (sleep 0.1)
    (is (string= (format nil "hd~%  one~%> two") (btext buf)))
    (multiple-value-bind (l c) (pine.editor.ask:ask buf :point)
      (declare (ignore c))
      (is (= 2 l)))
    (pine.editor.command::call-command "layout-activate")
    (is (eq :two fired))
    (sento.actor:tell buf '(:reproject :width 20)) (sleep 0.1)
    (is (= 20 (pine.text.buffer:buffer-local
               (sento.actor:ask-s buf '(:get-snapshot) :time-out 5)
               :layout-width)))))

(defun u (form)
  (let ((*package* (find-package :pine.user)))
    (eval (read-from-string form))))

(test (user-language :depends-on layout-buffers)
  "The pine.user authoring forms drive the real dispatch: keys, minor and
major modes, variables, css rules, tool buffers, prompts."
  (u "(defvar *ran* nil)")
  (u "(defcommand \"user-probe-cmd\" () (setf *ran* :yes))")
  (u "(global-set-key (kbd \"C-c p\") \"user-probe-cmd\")")
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch"))
  (key "C-c") (key "p") (sleep 0.05)
  (is (eq :yes (symbol-value (find-symbol "*RAN*" :pine.user))))
  (u "(defvar *min* nil)")
  (u "(defcommand \"user-min-cmd\" () (setf *min* :hit))")
  (u "(defminor user-probe-minor (:precedence 12))")
  (u "(define-key (keymap :user-probe-minor) (kbd \"z\") \"user-min-cmd\")")
  (is (null (pine.editor.command::key-binding *client* (pine.editor.key::parse-key "z"))))
  (u "(enable-minor-mode :user-probe-minor)")
  (is (equal "user-min-cmd" (pine.editor.command::key-binding *client* (pine.editor.key::parse-key "z"))))
  (u "(disable-minor-mode :user-probe-minor)")
  (is (null (pine.editor.command::key-binding *client* (pine.editor.key::parse-key "z"))))
  (u "(defmode user-probe-mode (:parent :text-mode :indicator \"UP\"))")
  (u "(auto-mode \"upx\" :user-probe-mode)")
  (is (eq :user-probe-mode (pine.editor.mode::mode-for-file "/tmp/x.upx")))
  (u "(set-buffer-mode (buffer \"scratch\") :user-probe-mode)")
  (is (eq :user-probe-mode
          (pine.text.buffer:buffer-local
           (sento.actor:ask-s (pine.editor.frame::buffer "scratch") '(:get-state) :time-out 5)
           :mode)))
  (u "(set-buffer-mode (buffer \"scratch\") :text-mode)")
  (u "(defonce :user-probe-var :default 1 :documentation \"probe\")")
  (u "(setf (var :user-probe-var) 42)")
  (is (eql 42 (u "(var :user-probe-var)")))
  (u "(defonce :user-probe-var :default 99)")
  (is (eql 42 (u "(var :user-probe-var)")))
  (u "(defrules (\".uprobe\" :color (color :accent)))")
  (multiple-value-bind (rows root)
      (pine.ui.cells:render (pine.ui.build:label "x" :class "uprobe") 6)
    (declare (ignore root))
    (is (equal (multiple-value-bind (r g b)
                   (pine.ui.face:hex-rgb (pine.ui.face:color :accent))
                 (list r g b))
               (subseq (rest (first (cdr (first rows)))) 0 3))))
  (u "(defvar *tool* nil)")
  (u "(show-layout \"*user-tool*\"
        (lambda (state) (declare (ignore state))
          (column :align :stretch
            (label \"tool\" :class \"help-head\")
            (choice :data (lambda () (setf *tool* :a)) (label \"a\"))
            (choice :data (lambda () (setf *tool* :b)) (label \"b\")))))")
  (sleep 0.15)
  (is (string= (format nil "tool~%> a~%  b")
               (btext (pine.editor.frame::buffer "*user-tool*"))))
  (pine.editor.command::call-command "layout-next")
  (pine.editor.command::call-command "layout-activate") (sleep 0.05)
  (is (eq :b (symbol-value (find-symbol "*TOOL*" :pine.user))))
  (u "(defvar *picked* :none)")
  (u "(defcommand \"user-pick\" ()
        (completing-read \"pick: \" (list \"xx\" \"yy\")
          (lambda (r) (setf *picked* r) (message (format nil \"got ~a\" r)))))")
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch"))
  (pine.editor.command::call-command "user-pick") (sleep 0.1)
  (key "y") (key "y") (sleep 0.1) (key "Return") (sleep 0.1)
  (is (equal "yy" (symbol-value (find-symbol "*PICKED*" :pine.user))))
  (is (string= "got yy" (pine.editor.echo:current-message))))

(test (chord-across-keymaps :depends-on user-language)
  "A mode's own C-c prefix must not hide global C-c chords: dispatch keeps
every active keymap's continuation live, the first complete binding wins,
and a dead-end chord echoes undefined instead of self-inserting."
  (u "(defvar *chord* nil)")
  (u "(defcommand chord-global () (setf *chord* :global))")
  (u "(defcommand chord-mode () (setf *chord* :mode))")
  (u "(defmode chord-probe-mode (:parent :text-mode))")
  (u "(define-key (keymap :chord-probe-mode) (kbd \"C-c C-q\") 'chord-mode)")
  (u "(global-set-key (kbd \"C-c q\") 'chord-global)")
  (u "(set-buffer-mode (buffer \"scratch\") :chord-probe-mode)")
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch"))
  (key "C-c")
  (is (equal "C-c" (pine.editor.ask:ask :client :pending-keys)))
  (key "q") (sleep 0.05)
  (is (eq :global (symbol-value (find-symbol "*CHORD*" :pine.user))))
  (key "C-c") (key "C-q") (sleep 0.05)
  (is (eq :mode (symbol-value (find-symbol "*CHORD*" :pine.user))))
  (let ((before (pine.editor.ask:ask (pine.editor.frame::buffer "scratch") :text)))
    (key "C-c") (key "j") (sleep 0.05)
    (is (equal before (pine.editor.ask:ask (pine.editor.frame::buffer "scratch") :text)))
    (is (search "undefined" (pine.editor.echo:current-message))))
  (u "(set-buffer-mode (buffer \"scratch\") :text-mode)"))

(test (persistence :depends-on chord-across-keymaps)
  "The store-backed behaviors end to end: persisted vars and refs reseed
after a simulated restart, find-file records recents and restores the saved
place, kills reach the store, prompt history recalls with M-p."
  (u "(defonce :persist-probe :default 1 :persist t)")
  (u "(setf (var :persist-probe) 5)")
  (is (eql 5 (pine.state.store:store '(:var :persist-probe))))
  (remhash :persist-probe pine.state.var::*variables*)
  (u "(defonce :persist-probe :default 1 :persist t)")
  (is (eql 5 (u "(var :persist-probe)")))
  (u "(defref :persist-ref-probe 0 :persist t)")
  (u "(setf (ref :persist-ref-probe) 9)")
  (is (eql 9 (pine.state.store:store '(:ref :persist-ref-probe))))
  (remhash :persist-ref-probe pine.state.ref::*refs*)
  (u "(defref :persist-ref-probe 0 :persist t)")
  (is (eql 9 (u "(ref :persist-ref-probe)")))
  (pine.editor.kill-ring::kill-ring-push "persist-kill-probe")
  (is (member "persist-kill-probe" (pine.state.store:store :kill-ring) :test #'equal))
  (let ((tmp "/tmp/pine-place-probe.txt"))
    (with-open-file (s tmp :direction :output :if-exists :supersede)
      (format s "one~%two~%three~%"))
    (pine.editor.file::find-file tmp) (sleep 0.15)
    (is (member tmp (pine.state.store:store-items :recent-files) :test #'equal))
    (let ((buf (pine.editor.frame::buffer "pine-place-probe.txt")))
      (sento.actor:tell buf '(:move-point :line 2 :col 1)) (sleep 0.1)
      (setf (pine.editor.frame::current-buffer *client*) buf)
      (pine.editor.file::save-current-buffer) (sleep 0.1)
      (is (equal '(2 1) (pine.state.store:store (list :place tmp)))))
    (pine.editor.frame::kill-buffer "pine-place-probe.txt") (sleep 0.1)
    (pine.editor.file::find-file tmp) (sleep 0.15)
    (multiple-value-bind (l c)
        (pine.editor.ask:ask (pine.editor.frame::buffer "pine-place-probe.txt") :point)
      (is (= 2 l))
      (is (= 1 c)))
    (pine.editor.frame::kill-buffer "pine-place-probe.txt") (sleep 0.1))
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch"))
  (pine.editor.command::call-command "execute-command") (sleep 0.1)
  (dolist (ch '("l" "i" "s" "t" "-" "b" "u" "f" "f" "e" "r" "s")) (key ch))
  (key "Return") (sleep 0.1)
  (is (member "list-buffers" (pine.state.store:store-items :commands) :test #'equal))
  (pine.editor.command::call-command "execute-command") (sleep 0.1)
  (key "M-p") (sleep 0.1)
  (is (equal "list-buffers" (mbtext)))
  (key "Escape") (sleep 0.1))

(test (world-save :depends-on persistence)
  "The world round-trips: splits + the open file + focus rebuild from the
store after a wipe (the restart / kill-editor case); scratch text rides its
contributor; foreign nodes refuse to serialize."
  (setf (pine.state.var:var :world-save) t)
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch"))
  (pine.editor.session::%seed-editor-tree *client* :world nil)
  (pine.ui.render:relayout)
  (let ((tmp "/tmp/pine-world-probe.txt"))
    (with-open-file (s tmp :direction :output :if-exists :supersede)
      (format s "alpha~%beta~%"))
    (pine.editor.command::call-command "split-window-below") (sleep 0.1)
    (pine.editor.file::find-file tmp) (sleep 0.15)
    (pine.editor.command::call-command "split-window-right") (sleep 0.1)
    (pine.state.world:save-world)
    (let ((arr (pine.state.store:store '(:world :arrangement)))
          (bufs (pine.state.store:store '(:world :buffers))))
      (is (eq :column (first (getf arr :tree))))
      (is (equal "pine-world-probe.txt" (getf arr :current)))
      (is (assoc tmp bufs :test #'equal))
      (pine.editor.frame::kill-buffer "pine-world-probe.txt") (sleep 0.1)
      (pine.editor.session::%seed-editor-tree *client* :world nil)
      (pine.ui.render:relayout)
      (is (= 1 (length (pine.editor.window::%editor-leaves *client*))))
      (setf (pine.state.store:store '(:world :arrangement)) arr)
      (pine.state.world:restore-world :buffers) (sleep 0.15)
      (pine.editor.session::%seed-editor-tree *client*)
      (pine.ui.render:relayout)
      (let* ((leaves (pine.editor.window::%editor-leaves *client*))
             (names (mapcar (lambda (l)
                              (pine.text.window:window-name (pine.ui.node:window-of l)))
                            leaves)))
        (is (= 3 (length leaves)))
        (is (= 2 (count "pine-world-probe.txt" names :test #'equal)))
        (is (equal "pine-world-probe.txt"
                   (pine.text.window:window-name (pine.editor.frame::focused-window *client*))))
        (is (string= "alpha"
                     (subseq (btext (pine.editor.frame::buffer "pine-world-probe.txt"))
                             0 5))))))
  (let ((scratch (pine.editor.frame::buffer "scratch")))
    (sento.actor:tell scratch '(:replace-content :content "world-scratch"))
    (sleep 0.1)
    (pine.state.world:save-world :scratch)
    (sento.actor:tell scratch '(:replace-content :content "")) (sleep 0.1)
    (pine.state.world:restore-world :scratch) (sleep 0.1)
    (is (search "world-scratch" (btext scratch))))
  (is (null (pine.editor.session::%tree->form (pine.ui.build:label "x"))))
  (pine.editor.frame::kill-buffer "pine-world-probe.txt")
  (setf (pine.state.var:var :world-save) nil)
  (pine.editor.session::%seed-editor-tree *client* :world nil)
  (pine.ui.render:relayout)
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch")))

(test (examples-init :depends-on user-language)
  "The shipped worked example loads clean and its definitions land."
  (finishes
    (load (merge-pathnames "../examples/init.lisp"
                           #.(or *compile-file-truename* *load-truename*))))
  (is (not (null (pine.editor.mode::find-mode :todo-mode))))
  (is (eq :todo-mode (pine.editor.mode::mode-for-file "/x.todo")))
  (is (equal "hi" (u "(var :greeting)"))))

(test (live-tree :depends-on examples-init)
  "The live editor tree: default seed, explicit-buffer windows, splits, focus,
modeline follow, layout-buffer embeds."
  (let* ((f (pine.editor.frame::frame *client*))
         (scratch (pine.editor.frame::buffer "scratch"))
         (b2 (pine.editor.frame::make-buffer "editor-b2")))
    (setf (pine.text.window:frame-cols f) 40 (pine.text.window:frame-rows f) 12)
    (pine.editor.frame::set-buffer-mode b2 :text-mode)
    (sento.actor:tell b2 (list :insert :text "beta-two"))
    (sleep 0.1)
    (pine.editor.session::%seed-editor-tree *client*)
    (let ((tree (pine.ui.render:refresh-editor-tree *client*))
          (leaves (pine.editor.window::%editor-leaves *client*)))
      (is (not (null tree)))
      (is (= 1 (length leaves)))
      (is (= 10 (length (pine.ui.node:window-rows (first leaves))))))
    (setf (pine.editor.frame::windows *client*) nil
          (pine.editor.frame::focused-window *client*) nil)
    (let* ((wa (pine.editor.session:editor-window-node "scratch" :expand 1))
           (wb (pine.editor.session:editor-window-node "editor-b2" :expand 1))
           (tree (pine.ui.build:column :align :stretch
                   (pine.ui.build:row :align :stretch :expand 1 wa wb)
                   (pine.editor.session:editor-echo-node)
                   (pine.editor.session:editor-modeline-node))))
      (setf (pine.editor.frame::arrangement *client*) tree)
      (pine.editor.frame::focus-window (pine.ui.node:window-of wa))
      (setf (pine.editor.frame::current-buffer *client*)
            (pine.text.window:buffer-ref (pine.ui.node:window-of wa)))
      (sleep 0.2)
      (pine.ui.render:refresh-editor-tree *client*)
      (is (search "beta-two" (car (first (pine.ui.node:window-rows wb))))))
    (pine.editor.session::%seed-editor-tree *client*)
    (pine.ui.render:relayout)
    (pine.editor.command::call-command "split-window-below")
    (is (= 2 (length (pine.editor.window::%editor-leaves *client*))))
    (pine.editor.command::call-command "other-window")
    (let ((buf (pine.editor.frame::switch-buffer "editor-b2")))
      (sento.actor:tell (pine.editor.frame::renderer *client*)
                        (list :switch-buffer :buffer buf :name "editor-b2"))
      (pine.ui.render:subscribe-to-buffer buf))
    (sleep 0.15)
    (key "x") (sleep 0.15)
    (is (search "x" (btext b2)))
    (is (not (search "x" (btext scratch))))
    (pine.ui.render:refresh-editor-tree *client*)
    (let ((ml (find :modeline (pine.ui.render:%window-leaves
                               (pine.editor.frame::arrangement *client*))
                    :key #'pine.ui.node:window-kind)))
      (is (search "editor-b2" (car (first (pine.ui.node:window-rows ml)))))
      (pine.editor.command::call-command "other-window")
      (pine.ui.render:refresh-editor-tree *client*)
      (is (search "scratch" (car (first (pine.ui.node:window-rows ml))))))
    (pine.editor.command::call-command "delete-other-windows")
    (is (= 1 (length (pine.editor.window::%editor-leaves *client*))))
    (is (eq scratch (pine.text.window:buffer-ref (pine.editor.frame::focused-window *client*))))
    (let ((prev pine.editor.frame::*client*))
      (setf pine.editor.frame::*client* nil)
      (unwind-protect
           (let ((node (pine.editor.session:editor-window-node "editor-b2")))
             (is (search "beta-two" (car (first (pine.ui.node:window-rows node))))))
        (setf pine.editor.frame::*client* prev)))
    (pine.editor.layout:show-layout "*wt-probe*"
      (lambda (state) (declare (ignore state))
        (pine.ui.build:column :align :stretch
          (pine.ui.build:label "wt" :face :keyword)
          (pine.editor.session:editor-window-node "editor-b2"))))
    (sleep 0.3)
    (let ((tx (btext (pine.editor.frame::buffer "*wt-probe*"))))
      (is (and (stringp tx) (search "wt" tx))))))

(test (symbol-commands :depends-on user-language)
  "Commands answer to symbols in definition, binding, and calling."
  (u "(defcommand sym-probe () (setf *ran* :sym))")
  (u "(global-set-key (kbd \"C-c y\") 'sym-probe)")
  (setf (pine.editor.frame::current-buffer *client*) (pine.editor.frame::buffer "scratch"))
  (key "C-c") (key "y") (sleep 0.05)
  (is (eq :sym (symbol-value (find-symbol "*RAN*" :pine.user))))
  (u "(setf *ran* nil)")
  (pine.editor.command::call-command 'sym-probe)
  (is (eq :sym (symbol-value (find-symbol "*RAN*" :pine.user)))))

(test (overlays :depends-on live-tree)
  "The overlay primitive: a per-line annotation renders after the line's
text and dies on the next edit."
  (let ((ob (pine.editor.frame::make-buffer "overlay-probe")))
    (pine.editor.frame::set-buffer-mode ob :text-mode)
    (sento.actor:tell ob (list :insert :text "abc"))
    (sleep 0.1)
    (sento.actor:tell ob (list :overlay :line 0 :text "=> 3"))
    (sleep 0.1)
    (setf (pine.editor.frame::windows *client*) nil
          (pine.editor.frame::focused-window *client*) nil)
    (let* ((wn (pine.editor.session:editor-window-node "overlay-probe" :expand 1))
           (tree (pine.ui.build:column :align :stretch
                   wn (pine.editor.session:editor-echo-node)
                   (pine.editor.session:editor-modeline-node))))
      (setf (pine.editor.frame::arrangement *client*) tree)
      (pine.editor.frame::focus-window (pine.ui.node:window-of wn))
      (setf (pine.editor.frame::current-buffer *client*) ob)
      (sleep 0.2)
      (pine.ui.render:refresh-editor-tree *client*)
      (is (search "=> 3" (car (first (pine.ui.node:window-rows wn)))))
      (sento.actor:tell ob (list :insert :text "d"))
      (sleep 0.15)
      (pine.ui.render:refresh-editor-tree *client*)
      (is (not (search "=>" (car (first (pine.ui.node:window-rows wn)))))))))

(test (inline-eval :depends-on overlays)
  "eval-last-sexp leaves its result inline on the form's line."
  (let ((eb (pine.editor.frame::make-buffer "eval-probe")))
    (pine.editor.frame::set-buffer-mode eb :text-mode)
    (setf (pine.editor.frame::current-buffer *client*) eb)
    (sento.actor:tell eb (list :insert :text "(+ 1 2)"))
    (sleep 0.1)
    (pine.editor.evaluate:eval-last-sexp)
    (sleep 0.5)
    (let ((ovs (pine.text.buffer:buffer-local
                (sento.actor:ask-s eb '(:get-state) :time-out 5) :overlays)))
      (is (and ovs (search "=> 3" (first (fset:@ ovs 0))) t)))))

(test (kill-yank :depends-on live-tree)
  "kill/yank round-trips multi-line text with its line structure."
  (let ((kb (pine.editor.frame::make-buffer "yank-probe")))
    (pine.editor.frame::set-buffer-mode kb :text-mode)
    (setf (pine.editor.frame::current-buffer *client*) kb)
    (sento.actor:tell kb (list :insert :text (format nil "alpha~%beta~%gamma")))
    (sleep 0.1)
    (is (string= (format nil "alpha~%beta~%gamma") (btext kb)))
    (sento.actor:tell kb (list :move-point :line 0 :col 0))
    (sleep 0.05)
    (pine.editor.command::call-command "set-mark")
    (sento.actor:tell kb (list :move-point :line 2 :col 5))
    (sleep 0.05)
    (pine.editor.command::call-command "kill-region")
    (sleep 0.1)
    (is (string= "" (btext kb)))
    (pine.editor.command::call-command "yank")
    (sleep 0.1)
    (is (string= (format nil "alpha~%beta~%gamma") (btext kb)))))

(test flex-rounding
  "Two half-slack expanders must not round the tail child off the rect."
  (ensure-editor-env)
  (multiple-value-bind (rows tree)
      (pine.ui.cells:render
       (pine.ui.build:column :align :stretch
         (pine.ui.build:label "a" :expand 1)
         (pine.ui.build:label "b" :expand 1)
         (pine.ui.build:label "tail"))
       10 :height 10)
    (declare (ignore tree))
    (is (string= "tail" (string-trim " " (car (nth 9 rows)))))))

(test language-surface
  "current and set! are gone from the language."
  (is (null (find-symbol "CURRENT" :pine.user)))
  (is (null (find-symbol "SET!" :pine.user))))

(test rules-wire
  "add-rules broadcasts the merged user rules to every attached app."
  (ensure-editor-env)
  (let* ((got nil)
         (sys (pine.core.server:actor-system *server*))
         (display (sento.actor-context:actor-of sys
                    :name (format nil "rules-probe-~a" (gensym))
                    :receive (lambda (msg)
                               (when (eq (first msg) :rules)
                                 (setf got (getf (rest msg) :rules)))
                               nil)))
         (ac (pine.core.attach::make-attached-client
              :id 999 :kind :probe :display display)))
    (push ac pine.core.attach:*clients*)
    (unwind-protect
         (progn
           (pine.ui.rules:add-rules '((".wire-probe" (:opacity "0.5"))))
           (sleep 0.2)
           (is (find ".wire-probe" got :key #'first :test #'string=)))
      (setf pine.core.attach:*clients* (remove ac pine.core.attach:*clients*)))))
