(in-package :pine.test)

(def-suite* :pine.editor :in :pine)

;;;; The editor over a real server and real buffer actors. Everything here
;;;; runs against the shared substrate through the SUBSTRATE fixture, which
;;;; puts the session back afterwards.

(test the-minibuffer-is-a-real-buffer
  (with-fixture substrate ()
    (let ((chosen :none))
      (pine.editor.minibuffer:completing-read
       "M-x " '("forward-word" "backward-word" "kill-line")
       (lambda (r) (setf chosen r)))
      (sleep 0.15)
      (is (eq (pine.editor.frame::current-buffer *client*)
              (pine.editor.frame::minibuffer-buffer *client*)))
      (type-text "abc")
      (is (string= "abc" (minibuffer-input)))
      (press* "C-a" "C-f" "X")
      (is (string= "aXbc" (minibuffer-input)))
      (is (= 2 (minibuffer-column)))
      (press* "C-e" "BackSpace")
      (is (string= "aXb" (minibuffer-input)))
      (press* "C-a" "C-k")
      (is (string= "" (minibuffer-input)))
      (type-text "forward")
      (sleep 0.15)
      (is (equal '("forward-word")
                 (mapcar #'pine.editor.completion:candidate-string
                         (pine.editor.frame::filtered
                          (pine.editor.minibuffer:completion)))))
      (press "Return")
      (sleep 0.15)
      (is (string= "forward-word" chosen))
      (is (not (eq (pine.editor.frame::current-buffer *client*)
                   (pine.editor.frame::minibuffer-buffer *client*)))))))

(test the-completion-popup-styles-the-selected-row
  (with-fixture substrate ()
    (pine.editor.minibuffer:completing-read "M-x " '("aaa" "bbb") (lambda (r) r))
    (sleep 0.15)
    (let ((rows (pine.editor.frame::popup-rows (pine.editor.minibuffer:completion))))
      (is (not (null rows)))
      (is (search "aaa" (car (first rows))))
      (is (equal (multiple-value-list
                  (pine.ui.face:hex-rgb (pine.ui.face:color :bg-active)))
                 (subseq (rest (first (cdr (first rows)))) 3 6))))
    (press "C-g")))

(test a-prompt-fired-over-a-prompt-keeps-the-original-return-buffer
  (with-fixture substrate ()
    (let ((file-buf (pine.editor.frame::current-buffer *client*)))
      (pine.editor.minibuffer:completing-read "M-x " '("one" "two") (lambda (r) r))
      (sleep 0.1)
      (pine.editor.minibuffer:completing-read "M-x " '("three") (lambda (r) r))
      (sleep 0.1)
      (is (eq file-buf (pine.editor.frame::saved-buffer *client*)))
      (pine.editor.minibuffer:minibuffer-abort)
      (sleep 0.1)
      (is (eq file-buf (pine.editor.frame::current-buffer *client*)))
      (press "q")
      (sleep 0.15)
      (is (search "q" (btext file-buf)))
      (press "BackSpace"))))

(test c-g-aborts-a-prompt-without-firing-its-callback
  (with-fixture substrate ()
    (let ((chosen :none))
      (pine.editor.minibuffer:completing-read "M-x " '("aaa" "bbb")
                                              (lambda (r) (setf chosen r)))
      (sleep 0.1)
      (press* "a" "C-g")
      (sleep 0.1)
      (is (eq :none chosen))
      (is (not (eq (pine.editor.frame::current-buffer *client*)
                   (pine.editor.frame::minibuffer-buffer *client*))))
      (is (null (pine.editor.frame::popup-rows
                 (pine.editor.minibuffer:completion)))))))

(test a-failing-edit-surfaces-with-a-retry-and-the-buffer-survives
  (with-fixture substrate ()
    (let ((buf (pine.editor.frame::make-buffer "err-scratch"))
          (seen nil))
      (pine.editor.frame::set-buffer-mode buf :text-mode)
      (sento.actor:tell buf (list :insert :text "hello"))
      (sleep 0.1)
      (setf pine.core.eval:*on-debug*
            (lambda (ev) (setf seen ev) (pine.core.eval:pick-restart ev "ABORT")))
      (sento.actor:tell buf (list :insert :text 42))
      (sleep 0.25)
      (is (not (null seen)))
      (is (eq :error (pine.core.eval:evaluation-status seen)))
      (is (string= "hello" (btext buf)))
      (is (member "RETRY" (mapcar #'first (pine.core.eval:evaluation-restarts seen))
                  :test #'string=))
      (sento.actor:tell buf (list :insert :text "!"))
      (sleep 0.15)
      (is (string= "hello!" (btext buf))))))

(test a-failing-command-routes-by-debug-on-error
  (with-fixture substrate ()
    (let ((seen nil))
      (pine.editor.command::define-command "probe-boom" () (error "boom"))
      (setf pine.core.eval:*on-debug* (lambda (ev) (setf seen ev)))
      (setf (pine.state.var:var :debug-on-error) t)
      (pine.editor.command::call-command "probe-boom")
      (is (not (null seen)))
      (setf seen nil)
      (setf (pine.state.var:var :debug-on-error) nil)
      (pine.editor.command::call-command "probe-boom")
      (is (null seen))
      (is (search "boom" (pine.editor.echo:current-message))))))

(test concurrent-faults-coexist-and-tab-pages-between-them
  (with-fixture substrate ()
    (pine.editor.debugger:agent-debug-surface
     (list :agent-debug :agent "alpha" :eval-id 1 :condition "boom-a"
           :restarts (list "RETRY" "ABORT")))
    (pine.editor.debugger:agent-debug-surface
     (list :agent-debug :agent "beta" :eval-id 2 :condition "boom-b"
           :restarts (list "ABORT")))
    (sleep 0.1)
    (is (= 2 (length pine.editor.debugger:*debugger-sessions*)))
    (is (string= "beta" (pine.editor.debugger::dbg-session-agent
                         pine.editor.debugger:*attended-session*)))
    (is (equal "beta" pine.editor.target:*eval-target*))
    (let ((text (btext "*debugger*")))
      (is (search "alpha" text))
      (is (search "beta" text))
      (is (search "[ABORT]" text)))
    (pine.editor.command::call-command "debugger-next-session")
    (sleep 0.05)
    (is (string= "alpha" (pine.editor.debugger::dbg-session-agent
                          pine.editor.debugger:*attended-session*)))
    (is (equal "alpha" pine.editor.target:*eval-target*))
    (pine.editor.command::call-command "layout-next")
    (sleep 0.1)
    (pine.editor.command::call-command "layout-activate")
    (sleep 0.05)
    (is (= 1 (length pine.editor.debugger:*debugger-sessions*)))
    (pine.editor.debugger:invoke-pending-restart "ABORT")
    (sleep 0.05)
    (is (= 0 (length pine.editor.debugger:*debugger-sessions*)))
    (is (null pine.editor.debugger:*attended-session*))
    (is (eq :local pine.editor.target:*eval-target*))))

(test eval-in-target-local-runs-through-the-one-eval-path
  (with-fixture substrate ()
    (let ((done :none))
      (pine.editor.target:eval-in-target
       "(+ 1 2)" (find-package :cl-user)
       :on-done (lambda (ev) (setf done (first (pine.core.eval:evaluation-values ev)))))
      (sleep 0.3)
      (is (= 3 done)))))

(test a-layout-buffer-renders-selects-activates-and-reprojects
  (with-fixture substrate ()
    (let ((fired nil)
          (buf (pine.editor.frame::make-buffer "layout-probe")))
      (sento.actor:tell buf
                        (list :set-layout :width 12 :builder
                              (lambda (state)
                                (declare (ignore state))
                                (pine.ui.build:column
                                 :align :stretch
                                 (pine.ui.build:label "hd" :face :keyword)
                                 (pine.ui.build:choice :data (lambda () (setf fired :one))
                                                       (pine.ui.build:label "one"))
                                 (pine.ui.build:choice :data (lambda () (setf fired :two))
                                                       (pine.ui.build:label "two"))))))
      (sleep 0.15)
      (is (string= (format nil "hd~%> one~%  two") (btext buf)))
      (setf (pine.editor.frame::current-buffer *client*) buf)
      (pine.editor.command::call-command "layout-next")
      (sleep 0.1)
      (is (string= (format nil "hd~%  one~%> two") (btext buf)))
      (multiple-value-bind (l c) (pine.editor.ask:ask buf :point)
        (declare (ignore c))
        (is (= 2 l)))
      (pine.editor.command::call-command "layout-activate")
      (is (eq :two fired))
      (sento.actor:tell buf '(:reproject :width 20))
      (sleep 0.1)
      (is (= 20 (pine.text.buffer:buffer-local (bsnap buf) :layout-width))))))

(test the-user-language-drives-the-real-dispatch
  (with-fixture substrate ()
    (in-user "(defvar *ran* nil)")
    (in-user "(defcommand \"user-probe-cmd\" () (setf *ran* :yes))")
    (in-user "(global-set-key (kbd \"C-c p\") \"user-probe-cmd\")")
    (press* "C-c" "p")
    (is (eq :yes (user-value "*RAN*")))
    (in-user "(defvar *min* nil)")
    (in-user "(defcommand \"user-min-cmd\" () (setf *min* :hit))")
    (in-user "(defminor user-probe-minor (:precedence 12))")
    (in-user "(define-key (keymap :user-probe-minor) (kbd \"z\") \"user-min-cmd\")")
    (is (null (pine.editor.command::key-binding
               *client* (pine.editor.key::parse-key "z"))))
    (in-user "(enable-minor-mode :user-probe-minor)")
    (is (equal "user-min-cmd" (pine.editor.command::key-binding
                               *client* (pine.editor.key::parse-key "z"))))
    (in-user "(disable-minor-mode :user-probe-minor)")
    (is (null (pine.editor.command::key-binding
               *client* (pine.editor.key::parse-key "z"))))
    (in-user "(defmode user-probe-mode (:parent :text-mode :indicator \"UP\"))")
    (in-user "(auto-mode \"upx\" :user-probe-mode)")
    (is (eq :user-probe-mode (pine.editor.mode::mode-for-file "/tmp/x.upx")))
    (in-user "(set-buffer-mode (buffer \"scratch\") :user-probe-mode)")
    (is (eq :user-probe-mode (pine.editor.ask:ask "scratch" :mode)))
    (in-user "(set-buffer-mode (buffer \"scratch\") :text-mode)")
    (in-user "(defonce :user-probe-var :default 1 :documentation \"probe\")")
    (in-user "(setf (var :user-probe-var) 42)")
    (is (= 42 (in-user "(var :user-probe-var)")))
    (in-user "(defonce :user-probe-var :default 99)")
    (is (= 42 (in-user "(var :user-probe-var)")))))

(test a-user-rule-styles-a-rendered-label
  (with-fixture substrate ()
    (in-user "(defrules (\".uprobe\" :color (color :accent)))")
    (let ((rows (pine.ui.cells:render
                 (pine.ui.build:label "x" :class "uprobe") 6)))
      (is (equal (multiple-value-list
                  (pine.ui.face:hex-rgb (pine.ui.face:color :accent)))
                 (subseq (rest (first (cdr (first rows)))) 0 3))))))

(test a-user-tool-buffer-selects-and-activates
  (with-fixture substrate ()
    (in-user "(defvar *tool* nil)")
    (in-user "(show-layout \"*user-tool*\"
        (lambda (state) (declare (ignore state))
          (column :align :stretch
            (label \"tool\" :class \"help-head\")
            (choice :data (lambda () (setf *tool* :a)) (label \"a\"))
            (choice :data (lambda () (setf *tool* :b)) (label \"b\")))))")
    (sleep 0.15)
    (is (string= (format nil "tool~%> a~%  b") (btext "*user-tool*")))
    (pine.editor.command::call-command "layout-next")
    (pine.editor.command::call-command "layout-activate")
    (sleep 0.05)
    (is (eq :b (user-value "*TOOL*")))))

(test a-user-command-can-prompt-and-echo-its-answer
  (with-fixture substrate ()
    (in-user "(defvar *picked* :none)")
    (in-user "(defcommand \"user-pick\" ()
        (completing-read \"pick: \" (list \"xx\" \"yy\")
          (lambda (r) (setf *picked* r) (message (format nil \"got ~a\" r)))))")
    (pine.editor.command::call-command "user-pick")
    (sleep 0.1)
    (type-text "yy")
    (sleep 0.1)
    (press "Return")
    (sleep 0.1)
    (is (string= "yy" (user-value "*PICKED*")))
    (is (string= "got yy" (pine.editor.echo:current-message)))))

(test a-command-answers-to-a-symbol-in-definition-binding-and-call
  (with-fixture substrate ()
    (in-user "(defvar *sym-ran* nil)")
    (in-user "(defcommand sym-probe () (setf *sym-ran* :sym))")
    (in-user "(global-set-key (kbd \"C-c y\") 'sym-probe)")
    (press* "C-c" "y")
    (is (eq :sym (user-value "*SYM-RAN*")))
    (in-user "(setf *sym-ran* nil)")
    (pine.editor.command::call-command 'sym-probe)
    (is (eq :sym (user-value "*SYM-RAN*")))))

(test current-and-set-bang-are-gone-from-the-language
  (is (null (find-symbol "CURRENT" :pine.user)))
  (is (null (find-symbol "SET!" :pine.user))))

(test add-rules-broadcasts-the-merged-set-to-every-attached-app
  (with-fixture substrate ()
    (let* ((got nil)
           (system (pine.core.server:actor-system *server*))
           (display (sento.actor-context:actor-of
                     system
                     :name (format nil "rules-probe-~a" (gensym))
                     :receive (lambda (msg)
                                (when (eq (first msg) :rules)
                                  (setf got (getf (rest msg) :rules)))
                                nil)))
           (client (pine.core.attach::make-attached-client
                    :id 999 :kind :probe :display display)))
      (push client pine.core.attach:*clients*)
      (unwind-protect
           (progn
             (pine.ui.rules:add-rules '((".wire-probe" (:opacity "0.5"))))
             (sleep 0.2)
             (is (find ".wire-probe" got :key #'first :test #'string=)))
        (setf pine.core.attach:*clients*
              (remove client pine.core.attach:*clients*))))))

(test persisted-variables-and-refs-reseed-after-a-restart
  (with-fixture substrate ()
    (in-user "(defonce :persist-probe :default 1 :persist t)")
    (in-user "(setf (var :persist-probe) 5)")
    (is (= 5 (pine.state.world:value '(:var :persist-probe))))
    (remhash :persist-probe pine.state.var::*variables*)
    (in-user "(defonce :persist-probe :default 1 :persist t)")
    (is (= 5 (in-user "(var :persist-probe)")))
    (in-user "(defref :persist-ref-probe 0 :persist t)")
    (in-user "(setf (ref :persist-ref-probe) 9)")
    (is (= 9 (pine.state.world:value '(:ref :persist-ref-probe))))
    (remhash :persist-ref-probe pine.state.ref::*refs*)
    (in-user "(defref :persist-ref-probe 0 :persist t)")
    (is (= 9 (in-user "(ref :persist-ref-probe)")))))

(test a-kill-reaches-the-store
  (with-fixture substrate ()
    (pine.editor.kill-ring::kill-ring-push "persist-kill-probe")
    (is (member "persist-kill-probe" (pine.state.world:value :kill-ring)
                :test #'equal))))

(test find-file-records-a-recent-and-restores-the-saved-place
  (with-fixture substrate ()
    (let ((path "/tmp/pine-place-probe.txt"))
      (with-open-file (s path :direction :output :if-exists :supersede)
        (format s "one~%two~%three~%"))
      (pine.editor.file::find-file path)
      (sleep 0.15)
      (is (member path (pine.state.world:items :recent-files) :test #'equal))
      (let ((buf (pine.editor.frame::buffer "pine-place-probe.txt")))
        (sento.actor:tell buf '(:move-point :line 2 :col 1))
        (sleep 0.1)
        (setf (pine.editor.frame::current-buffer *client*) buf)
        (pine.editor.file::save-current-buffer)
        (sleep 0.1)
        (is (equal '(2 1) (pine.state.world:value (list :place path)))))
      (pine.editor.frame::kill-buffer "pine-place-probe.txt")
      (sleep 0.1)
      (pine.editor.file::find-file path)
      (sleep 0.15)
      (multiple-value-bind (l c)
          (pine.editor.ask:ask "pine-place-probe.txt" :point)
        (is (equal '(2 1) (list l c))))
      (pine.editor.frame::kill-buffer "pine-place-probe.txt")
      (sleep 0.1))))

(test prompt-history-recalls-with-meta-p
  (with-fixture substrate ()
    (pine.editor.command::call-command "execute-command")
    (sleep 0.1)
    (type-text "list-buffers")
    (press "Return")
    (sleep 0.1)
    (is (member "list-buffers" (pine.state.world:items :commands) :test #'equal))
    (pine.editor.command::call-command "execute-command")
    (sleep 0.1)
    (press "M-p")
    (sleep 0.1)
    (is (string= "list-buffers" (minibuffer-input)))
    (press "Escape")
    (sleep 0.1)))

(test the-world-round-trips-the-splits-the-open-file-and-the-focus
  (with-fixture substrate ()
    (setf pine.state.world:*enabled* t)
    (pine.editor.session::%seed-editor-tree *client* :world nil)
    (pine.ui.render:relayout)
    (let ((path "/tmp/pine-world-probe.txt"))
      (with-open-file (s path :direction :output :if-exists :supersede)
        (format s "alpha~%beta~%"))
      (pine.editor.command::call-command "split-window-below")
      (sleep 0.1)
      (pine.editor.file::find-file path)
      (sleep 0.15)
      (pine.editor.command::call-command "split-window-right")
      (sleep 0.1)
      (pine.state.world:save)
      (let ((arrangement (pine.state.world:value :arrangement))
            (buffers (pine.state.world:value :buffers)))
        (is (eq :column (first (getf arrangement :tree))))
        (is (equal "pine-world-probe.txt" (getf arrangement :current)))
        (is (find path buffers :key (lambda (e) (getf e :path)) :test #'equal)
            "the world should hold the open file, saw ~s" buffers)
        (pine.editor.frame::kill-buffer "pine-world-probe.txt")
        (sleep 0.1)
        (pine.editor.session::%seed-editor-tree *client* :world nil)
        (pine.ui.render:relayout)
        (is (= 1 (length (pine.editor.window::%editor-leaves *client*))))
        (setf (pine.state.world:value :arrangement) arrangement)
        (pine.state.world:restore :buffers)
        (sleep 0.15)
        (pine.editor.session::%seed-editor-tree *client*)
        (pine.ui.render:relayout)
        (let* ((leaves (pine.editor.window::%editor-leaves *client*))
               (names (mapcar (lambda (leaf)
                                (pine.text.window:window-name
                                 (pine.ui.node:window-of leaf)))
                              leaves)))
          (is (= 3 (length leaves)))
          (is (= 2 (count "pine-world-probe.txt" names :test #'equal)))
          (is (equal "pine-world-probe.txt"
                     (pine.text.window:window-name
                      (pine.editor.frame::focused-window *client*))))
          (is (string= "alpha" (subseq (btext "pine-world-probe.txt") 0 5)))))
      (pine.editor.frame::kill-buffer "pine-world-probe.txt")
      (setf pine.state.world:*enabled* nil)
      (pine.editor.session::%seed-editor-tree *client* :world nil)
      (pine.ui.render:relayout))))

(test scratch-text-rides-its-own-world-contributor
  (with-fixture substrate ()
    (setf pine.state.world:*enabled* t)
    (let ((scratch (pine.editor.frame::buffer "scratch")))
      (sento.actor:tell scratch '(:replace-content :content "world-scratch"))
      (sleep 0.1)
      (pine.state.world:save :scratch)
      (sento.actor:tell scratch '(:replace-content :content ""))
      (sleep 0.1)
      (pine.state.world:restore :scratch)
      (sleep 0.1)
      (is (search "world-scratch" (btext scratch)))
      (sento.actor:tell scratch '(:replace-content :content ""))
      (sleep 0.1))
    (setf pine.state.world:*enabled* nil)))

(test the-arrangement-serializes-into-the-builder-language-and-back
  (with-fixture substrate ()
    (pine.editor.session::%seed-editor-tree *client* :world nil)
    (let ((form (pine.editor.session::%tree->form
                 (pine.editor.frame::arrangement *client*))))
      (is (eq :column (first form)))
      (is (member '(:echo) form :test #'equal))
      (is (find-if (lambda (part) (and (consp part) (eq :window (first part)))) form))
      (let ((rebuilt (pine.editor.session::%form->tree form)))
        (is (equal form (pine.editor.session::%tree->form rebuilt)))))))

(test a-node-outside-the-vocabulary-refuses-to-serialize
  (is (null (pine.editor.session::%tree->form (pine.ui.build:label "x")))))

(test the-shipped-example-loads-clean-and-its-definitions-land
  (with-fixture substrate ()
    (finishes
      (load (merge-pathnames "../examples/init.lisp"
                             #.(or *compile-file-truename* *load-truename*))))
    (is (not (null (pine.editor.mode::find-mode :todo-mode))))
    (is (eq :todo-mode (pine.editor.mode::mode-for-file "/x.todo")))
    (is (string= "hi" (in-user "(var :greeting)")))))

(test the-live-tree-seeds-splits-focuses-and-follows-the-modeline
  (with-fixture substrate ()
    (let* ((frame (pine.editor.frame::frame *client*))
           (scratch (pine.editor.frame::buffer "scratch"))
           (other (pine.editor.frame::make-buffer "editor-b2")))
      (setf (pine.text.window:frame-cols frame) 40
            (pine.text.window:frame-rows frame) 12)
      (pine.editor.frame::set-buffer-mode other :text-mode)
      (sento.actor:tell other (list :insert :text "beta-two"))
      (sleep 0.1)
      (pine.editor.session::%seed-editor-tree *client*)
      (let ((tree (pine.ui.render:refresh-editor-tree *client*))
            (leaves (pine.editor.window::%editor-leaves *client*)))
        (is (not (null tree)))
        (is (= 1 (length leaves)))
        (is (= 10 (length (pine.ui.node:window-rows (first leaves))))))
      (pine.editor.session::%seed-editor-tree *client*)
      (pine.ui.render:relayout)
      (pine.editor.command::call-command "split-window-below")
      (is (= 2 (length (pine.editor.window::%editor-leaves *client*))))
      (pine.editor.command::call-command "other-window")
      (let ((buf (pine.editor.frame::switch-buffer "editor-b2")))
        (sento.actor:tell (pine.editor.frame::renderer *client*)
                          (list :switch-buffer :buffer buf :name "editor-b2"))
        (pine.ui.render:subscribe-to-buffer buf))
      (sleep 0.15)
      (press "x")
      (sleep 0.15)
      (is (search "x" (btext other)))
      (is (not (search "x" (btext scratch))))
      (pine.ui.render:refresh-editor-tree *client*)
      (let ((modeline (find :modeline (pine.ui.render:window-leaves
                                       (pine.editor.frame::arrangement *client*))
                            :key #'pine.ui.node:window-kind)))
        (is (search "editor-b2" (car (first (pine.ui.node:window-rows modeline)))))
        (pine.editor.command::call-command "other-window")
        (pine.ui.render:refresh-editor-tree *client*)
        (is (search "scratch" (car (first (pine.ui.node:window-rows modeline))))))
      (pine.editor.command::call-command "delete-other-windows")
      (is (= 1 (length (pine.editor.window::%editor-leaves *client*))))
      (is (eq scratch (pine.text.window:buffer-ref
                       (pine.editor.frame::focused-window *client*)))))))

(test a-window-node-built-with-no-client-renders-once-at-build
  (with-fixture substrate ()
    (let ((other (pine.editor.frame::make-buffer "editor-b3")))
      (pine.editor.frame::set-buffer-mode other :text-mode)
      (sento.actor:tell other (list :insert :text "beta-three"))
      (sleep 0.1)
      (let ((pine.editor.frame::*client* nil))
        (let ((node (pine.editor.session:editor-window-node "editor-b3")))
          (is (search "beta-three"
                      (car (first (pine.ui.node:window-rows node))))))))))

(test an-overlay-renders-after-the-line-and-dies-on-the-next-edit
  (with-fixture substrate ()
    (let ((buf (pine.editor.frame::make-buffer "overlay-probe")))
      (pine.editor.frame::set-buffer-mode buf :text-mode)
      (sento.actor:tell buf (list :insert :text "abc"))
      (sleep 0.1)
      (sento.actor:tell buf (list :overlay :line 0 :text "=> 3"))
      (sleep 0.1)
      (setf (pine.editor.frame::windows *client*) nil
            (pine.editor.frame::focused-window *client*) nil)
      (let* ((node (pine.editor.session:editor-window-node "overlay-probe" :expand 1))
             (tree (pine.ui.build:column :align :stretch
                                         node
                                         (pine.editor.session:editor-echo-node)
                                         (pine.editor.session:editor-modeline-node))))
        (setf (pine.editor.frame::arrangement *client*) tree)
        (pine.editor.frame::focus-window (pine.ui.node:window-of node))
        (setf (pine.editor.frame::current-buffer *client*) buf)
        (sleep 0.2)
        (pine.ui.render:refresh-editor-tree *client*)
        (is (search "=> 3" (car (first (pine.ui.node:window-rows node)))))
        (sento.actor:tell buf (list :insert :text "d"))
        (sleep 0.15)
        (pine.ui.render:refresh-editor-tree *client*)
        (is (not (search "=>" (car (first (pine.ui.node:window-rows node))))))))
    (pine.editor.session::%seed-editor-tree *client* :world nil)
    (pine.ui.render:relayout)))

(test eval-last-sexp-leaves-its-result-inline
  (with-fixture substrate ()
    (let ((buf (pine.editor.frame::make-buffer "eval-probe")))
      (pine.editor.frame::set-buffer-mode buf :text-mode)
      (setf (pine.editor.frame::current-buffer *client*) buf)
      (sento.actor:tell buf (list :insert :text "(+ 1 2)"))
      (sleep 0.1)
      (pine.editor.evaluate:eval-last-sexp)
      (sleep 0.5)
      (let ((overlays (pine.text.buffer:buffer-local
                       (pine.core.actor:ask buf '(:get-state) :timeout 5)
                       :overlays)))
        (is (not (null overlays)))
        (is (search "=> 3" (first (fset:@ overlays 0))))))))

(test kill-and-yank-round-trip-multi-line-text
  (with-fixture substrate ()
    (let ((buf (pine.editor.frame::make-buffer "yank-probe")))
      (pine.editor.frame::set-buffer-mode buf :text-mode)
      (setf (pine.editor.frame::current-buffer *client*) buf)
      (sento.actor:tell buf (list :insert :text (format nil "alpha~%beta~%gamma")))
      (sleep 0.1)
      (is (string= (format nil "alpha~%beta~%gamma") (btext buf)))
      (sento.actor:tell buf (list :move-point :line 0 :col 0))
      (sleep 0.05)
      (pine.editor.command::call-command "set-mark")
      (sento.actor:tell buf (list :move-point :line 2 :col 5))
      (sleep 0.05)
      (pine.editor.command::call-command "kill-region")
      (sleep 0.1)
      (is (string= "" (btext buf)))
      (pine.editor.command::call-command "yank")
      (sleep 0.1)
      (is (string= (format nil "alpha~%beta~%gamma") (btext buf))))))

(test undo-and-redo-walk-the-edit-history
  (with-fixture substrate ()
    (let ((buf (pine.editor.frame::make-buffer "undo-probe")))
      (pine.editor.frame::set-buffer-mode buf :text-mode)
      (sento.actor:tell buf (list :insert :text "one"))
      (sleep 0.1)
      (sento.actor:tell buf (list :insert :text "-two"))
      (sleep 0.1)
      (is (string= "one-two" (btext buf)))
      (sento.actor:tell buf '(:undo))
      (sleep 0.1)
      (is (string= "one" (btext buf)))
      (sento.actor:tell buf '(:redo))
      (sleep 0.1)
      (is (string= "one-two" (btext buf))))))

(test a-lisp-buffer-indents-electrically-on-a-newline
  (with-fixture substrate ()
    (let ((buf (pine.editor.frame::make-buffer "indent-probe")))
      (pine.editor.frame::set-buffer-mode buf :lisp-mode)
      (setf (pine.editor.frame::current-buffer *client*) buf)
      (sento.actor:tell buf (list :replace-content
                                  :content (format nil "(defun f ()~%(bar))")))
      (sleep 0.15)
      (sento.actor:tell buf (list :move-point :line 0 :col 11))
      (sleep 0.05)
      (pine.editor.ask:tell buf :newline)
      ;; the line lands at once and the parser answers with its column, so the
      ;; indent is waited for rather than assumed to have already happened
      (is (wait-for (lambda ()
                      (multiple-value-bind (l c) (pine.editor.ask:ask buf :point)
                        (and (= 1 l) (= 2 c))))
                    :seconds 10)
          "the new line is indented into the defun body; point is at ~a"
          (multiple-value-list (pine.editor.ask:ask buf :point))))))
