(in-package :pine/test)

(def-suite* :pine/symbols :in :pine)

(defparameter +table+ "doc/symbols.md")

(defparameter +not-pine+ '("PINE/VT" "PINE/TEST"))

(defun %minep (name)
  (and (>= (length name) 4) (string= "PINE" name :end2 4)
       (notany (lambda (each)
                 (and (>= (length name) (length each))
                      (string= each name :end2 (length each))))
               +not-pine+)))

(defun %packages ()
  (sort (remove-if-not (lambda (p) (%minep (package-name p))) (list-all-packages))
        #'string< :key #'package-name))

(defun %externals (package)
  (let (out)
    (do-external-symbols (s package) (push s out))
    (sort out #'string< :key #'symbol-name)))

(defun %class-kind (class)
  (cond ((subtypep class 'condition) "condition")
        ((typep class 'structure-class) "struct")
        (t "class")))

(defun %kinds (symbol)
  (let ((found nil)
        (class (find-class symbol nil)))
    (when class (push (%class-kind class) found))
    (cond ((macro-function symbol) (push "macro" found))
          ((fboundp symbol)
           (push (if (typep (fdefinition symbol) 'generic-function) "generic" "function")
                 found)))
    (when (fboundp (list 'setf symbol)) (push "setf" found))
    (when (boundp symbol)
      (push (if (constantp symbol) "constant" "variable") found))
    (or (nreverse found) (list "symbol"))))

(defun %accessorp (kinds)
  (or (equal kinds '("generic" "setf")) (equal kinds '("function" "setf"))))

(defun %two-things-p (kinds)
  (and (rest kinds) (not (%accessorp kinds))))

(defun table ()
  (with-output-to-string (out)
    (format out "# pine, symbol by symbol~%~%")
    (format out "Generated by `tests/symbols.lisp`. `(pine/test::write-table)` ~
                 rewrites it; the suite fails when it is stale.~%~%")
    (format out "A row marked `!` is one symbol naming more than one thing.~%")
    (dolist (p (%packages))
      (let ((rows (loop :for s :in (%externals p)
                        :for kinds := (%kinds s)
                        :collect (list (string-downcase (symbol-name s))
                                       (format nil "~{~a~^ + ~}" kinds)
                                       (if (%two-things-p kinds) "!" "")))))
        (format out "~%## ~(~a~)~%~%" (package-name p))
        (if (null rows)
            (format out "Exports nothing.~%")
            (progn
              (format out "| symbol | kind | |~%|---|---|---|~%")
              (dolist (r rows)
                (format out "| `~a` | ~a | ~a |~%" (first r) (second r) (third r)))))))))

(defun %where ()
  (merge-pathnames +table+ (asdf:system-source-directory :pine)))

(defun write-table ()
  (let ((where (%where)))
    (with-open-file (out where :direction :output :if-exists :supersede
                               :if-does-not-exist :create :external-format :utf-8)
      (write-string (table) out))
    where))

(test every-exported-symbol-is-in-the-written-table
  "doc/symbols.md is the only written record of what pine exports."
  (let ((where (%where)))
    (is (probe-file where) "doc/symbols.md is missing: run (pine/test::write-table)")
    (when (probe-file where)
      (is (equal (table) (uiop:read-file-string where))
          "doc/symbols.md is stale: run (pine/test::write-table)"))))
