(defpackage #:pine/edit/commands
  (:use #:cl)
  (:local-nicknames (#:d #:pine/data) (#:node #:pine/fs/node)
                    (#:tree #:pine/fs/tree) (#:fault #:pine/run/fault)
                    (#:surface #:pine/ui/surface)
                    (#:command #:pine/run/command) (#:log #:pine/run/log)
                    (#:mode #:pine/text/mode) (#:doc #:pine/text/document)
                    (#:lines #:pine/text/lines)
                    (#:parser #:pine/text/ts/parser)
                    (#:runtime #:pine/text/ts/runtime)
                    (#:window #:pine/edit/window) (#:render #:pine/edit/render)
                    (#:prompt #:pine/edit/prompt))
  (:export #:commands #:kill #:yank #:times #:counting #:*kill-ring*))
(in-package #:pine/edit/commands)

(defvar *kill-ring* nil)
(defvar *kill-kept* 60)
(defvar *count* (d:box nil))

(defun %clip ()
  (tree:at nil "dev" "clip" "text"))

(defun kill (string)
  (let ((n (%clip)))
    (when n (fault:attempt (lambda () (setf (node:contents n) string)) "copying")))
  (push string *kill-ring*)
  (when (> (length *kill-ring*) *kill-kept*)
    (setf *kill-ring* (subseq *kill-ring* 0 *kill-kept*)))
  string)

(defun yank ()
  "What to put back: what the desktop is holding when that is not what pine killed
last, so what was copied in another program pastes here."
  (let* ((n (%clip))
         (theirs (and n (fault:attempt (lambda () (node:contents n)) "pasting"))))
    (if (and theirs (plusp (length theirs)) (not (equal theirs (first *kill-ring*))))
        theirs
        (first *kill-ring*))))

(defun counting () (d:held *count*))

(defun times (&optional (default 1))
  "How many times the next command runs, and forget it. A prefix argument is spent
by whoever asks for it."
  (let ((held (counting)))
    (d:put! *count* nil)
    (cond ((null held) default)
          ((eq held :more) 4)
          ((eq held :minus) -1)
          (t held))))

(defun %of () (doc:current))

(defun %lines (document) (d:held (doc:lines document)))

(defun %case-word (by)
  (let* ((document (%of)) (line (doc:at-line document)) (col (doc:at-col document)))
    (multiple-value-bind (to-line to-col)
        (lines:move-by :word (%lines document) line col 1)
      (when (= line to-line)
        (let ((word (doc:delete-region document line col to-line to-col)))
          (doc:insert document (funcall by word)))))))

(defun %go (document kind)
  (or (parser:motion document kind
                     (lambda (line col) (doc:goto document line col)))
      (log:note "the parse says nothing there")))

(defun %motion ()
  (command:defcommand "forward-sexp" () (:describes "over the form after point")
    (%go (%of) :forward-sexp))
  (command:defcommand "backward-sexp" ()
      (:describes "back over the form before point")
    (%go (%of) :backward-sexp))
  (command:defcommand "beginning-of-defun" ()
      (:describes "to the top of this definition")
    (%go (%of) :beginning-of-defun))
  (command:defcommand "end-of-defun" () (:describes "to the end of this definition")
    (%go (%of) :end-of-defun))
  (command:defcommand "mark-sexp" ()
      (:describes "the region is the form after point")
    (let ((document (%of)))
      (parser:motion document :forward-sexp
                     (lambda (line col)
                       (setf (doc:mark document) (doc:point document))
                       (doc:goto document line col)))))
  (command:defcommand "forward-char" () (:describes "point one character on")
    (doc:move (%of) :char (times)))
  (command:defcommand "backward-char" () (:describes "point one character back")
    (doc:move (%of) :char (- (times))))
  (command:defcommand "forward-word" () (:describes "point one word on")
    (doc:move (%of) :word (times)))
  (command:defcommand "backward-word" () (:describes "point one word back")
    (doc:move (%of) :word (- (times))))
  (command:defcommand "next-line" () (:describes "point one line down")
    (doc:move (%of) :line (times)))
  (command:defcommand "previous-line" () (:describes "point one line up")
    (doc:move (%of) :line (- (times))))
  (command:defcommand "beginning-of-line" () (:describes "point to column zero")
    (doc:goto (%of) (doc:at-line (%of)) 0))
  (command:defcommand "end-of-line" () (:describes "point to the end of the line")
    (doc:goto (%of) (doc:at-line (%of))
              (length (doc:line (%of) (doc:at-line (%of))))))
  (command:defcommand "beginning-of-document" ()
      (:describes "point to the first line")
    (doc:goto (%of) 0 0))
  (command:defcommand "end-of-document" () (:describes "point to the last line")
    (doc:move (%of) :text 1))
  (command:defcommand "goto-line" (line)
      (:describes "point to a line by number"
       :asks '((:prompt "Line: " :as :integer)))
    (let ((n (if (integerp line)
                 line
                 (parse-integer (princ-to-string line) :junk-allowed t))))
      (when n (doc:goto (%of) (max 0 (1- n)) 0))))
  (command:defcommand "universal-argument" ()
      (:describes "the next command, four times")
    (d:swap! *count* (lambda (had)
                       (cond ((null had) :more)
                             ((eq had :more) 16)
                             ((integerp had) (* had 4))
                             (t :more))))
    (log:note "C-u~@[ ~a~]" (counting)))
  (command:defcommand "negative-argument" ()
      (:describes "the next command, backwards")
    (d:swap! *count* (lambda (had) (if (integerp had) (- had) :minus)))
    (log:note "C--"))
  (dolist (n '(0 1 2 3 4 5 6 7 8 9))
    (let ((n n))
      (command:command
       (format nil "digit-argument-~d" n)
       (lambda ()
         (d:swap! *count* (lambda (had)
                            (cond ((integerp had) (+ (* 10 had) n))
                                  ((eq had :minus) (- n))
                                  (t n))))
         (log:note "C-u ~a" (counting)))
       :describes "a digit of the count the next command takes"))))

(defun %laying-out (document)
  (lambda (targets)
    (loop :for (line . at) :in targets
          :do (doc:indent-line document line at))))

(defun %indent (document from to)
  (render:indenting document from to (%laying-out document)))

(defun %editing ()
  (command:defcommand "newline" () (:describes "break the line at point")
    (let ((document (%of)))
      (doc:newline document)
      (%indent document (doc:at-line document) (doc:at-line document))
      (doc:point document)))
  (command:defcommand "indent-line" ()
      (:describes "indent this line as the parse says")
    (%indent (%of) (doc:at-line (%of)) (doc:at-line (%of))))
  (command:defcommand "undo" () (:describes "put back what the last edit changed")
    (doc:undo (%of)))
  (command:defcommand "redo" () (:describes "do again what undo put back")
    (doc:redo (%of)))
  (command:defcommand "delete-backward-char" ()
      (:describes "take the character before point")
    (doc:delete-back (%of)))
  (command:defcommand "delete-char" () (:describes "take the character at point")
    (let* ((document (%of))
           (line (doc:at-line document))
           (col (doc:at-col document)))
      (if (< col (length (doc:line document line)))
          (doc:delete-region document line col line (1+ col))
          (when (< (1+ line) (doc:line-count document))
            (doc:delete-region document line col (1+ line) 0)))))
  (command:defcommand "set-mark" () (:describes "put the mark at point")
    (setf (doc:mark (%of)) (doc:point (%of))))
  (command:defcommand "kill-region" () (:describes "take the region and keep it")
    (let* ((document (%of)) (taken (doc:region-of document)))
      (when taken
        (kill taken)
        (destructuring-bind (line col) (doc:mark document)
          (doc:delete-region document line col
                             (doc:at-line document) (doc:at-col document))
          (setf (doc:mark document) nil)))
      taken))
  (command:defcommand "copy-region" ()
      (:describes "keep the region without taking it")
    (let* ((document (%of)) (taken (doc:region-of document)))
      (when taken (kill taken) (setf (doc:mark document) nil))
      taken))
  (command:defcommand "yank" () (:describes "put back what was killed")
    (let ((held (yank)))
      (when held (doc:insert (%of) held))
      held))
  (command:defcommand "yank-pop" ()
      (:describes "the kill before the one just put back")
    (let ((held (second *kill-ring*)))
      (when held
        (setf *kill-ring* (append (rest *kill-ring*) (list (first *kill-ring*))))
        (doc:insert (%of) (first *kill-ring*)))
      held))
  (command:defcommand "kill-line" ()
      (:describes "take the rest of the line and keep it")
    (let* ((document (%of))
           (line (doc:at-line document))
           (col (doc:at-col document))
           (text (doc:line document line)))
      (kill (if (< col (length text))
                (doc:delete-region document line col line (length text))
                (when (< (1+ line) (doc:line-count document))
                  (doc:delete-region document line col (1+ line) 0))))))
  (command:defcommand "kill-word" ()
      (:describes "take the word after point and keep it")
    (let* ((document (%of))
           (line (doc:at-line document))
           (col (doc:at-col document)))
      (multiple-value-bind (to-line to-col)
          (lines:move-by :word (%lines document) line col 1)
        (kill (doc:delete-region document line col to-line to-col)))))
  (command:defcommand "backward-kill-word" ()
      (:describes "take the word before point and keep it")
    (let* ((document (%of))
           (line (doc:at-line document))
           (col (doc:at-col document)))
      (multiple-value-bind (from-line from-col)
          (lines:move-by :word (%lines document) line col -1)
        (kill (doc:delete-region document from-line from-col line col)))))
  (command:defcommand "open-line" ()
      (:describes "a fresh line below, point where it is")
    (let ((document (%of)))
      (doc:newline document)
      (doc:move document :char -1)))
  (command:defcommand "transpose-chars" ()
      (:describes "swap the two characters around point")
    (let* ((document (%of))
           (line (doc:at-line document))
           (col (doc:at-col document))
           (text (doc:line document line)))
      (when (and (plusp col) (<= col (length text)))
        (let ((taken (doc:delete-region document line (1- col) line col)))
          (doc:goto document line (min (length (doc:line document line)) col))
          (doc:insert document taken)))))
  (command:defcommand "mark-whole-document" ()
      (:describes "the region is everything")
    (let ((document (%of)))
      (setf (doc:mark document) (list 0 0))
      (doc:move document :text 1)))
  (command:defcommand "exchange-point-and-mark" ()
      (:describes "point and mark swap places")
    (let* ((document (%of)) (mark (doc:mark document)) (at (doc:point document)))
      (when mark
        (setf (doc:mark document) at)
        (doc:goto document (first mark) (second mark)))))
  (command:defcommand "indent-region" ()
      (:describes "indent every line of the region")
    (let* ((document (%of)) (span (doc:mark document)))
      (when span
        (%indent document
                 (min (first span) (doc:at-line document))
                 (max (first span) (doc:at-line document))))))
  (command:defcommand "format-document" () (:describes "indent every line of it")
    (let ((document (%of)))
      (%indent document 0 (max 0 (1- (doc:line-count document))))
      (doc:line-count document)))
  (command:defcommand "comment-line" ()
      (:describes "comment this line, or uncomment it")
    (let* ((document (%of))
           (line (doc:at-line document))
           (text (doc:line document line))
           (mark (or (mode:setting (doc:mode-of document) :comment) ";;"))
           (from (lines:indent text))
           (body (subseq text from)))
      (doc:goto document line 0)
      (doc:delete-region document line 0 line (length text))
      (doc:insert document
                  (concatenate 'string
                               (make-string from :initial-element #\Space)
                               (if (and (>= (length body) (length mark))
                                        (string= mark body :end2 (length mark)))
                                   (string-left-trim " " (subseq body (length mark)))
                                   (concatenate 'string mark " " body))))))
  (command:defcommand "upcase-word" ()
      (:describes "the word after point, in capitals")
    (%case-word #'string-upcase))
  (command:defcommand "downcase-word" ()
      (:describes "the word after point, in small letters")
    (%case-word #'string-downcase))
  (command:defcommand "capitalize-word" ()
      (:describes "the word after point, capitalised")
    (%case-word #'string-capitalize))
  (command:defcommand "insert-tab" () (:describes "a tab's worth of spaces")
    (let* ((document (%of))
           (width (max 1 (or (doc:setting document :tab-width) 8))))
      (doc:insert document (make-string width :initial-element #\Space))
      width))
  (command:defcommand "overwrite" () (:describes "type over what is there")
    (let* ((document (%of)) (on (not (doc:setting document :overwrite))))
      (setf (doc:setting document :overwrite) on)
      (log:note "overwrite is ~:[off~;on~]" on)
      on))
  (command:defcommand "refresh" () (:describes "draw everything again")
    (let ((n 0))
      (dolist (each (surface:surfaces) n)
        (fault:attempt (lambda () (node:stir each)) (node:name each))
        (incf n))))
  (command:defcommand "keyboard-quit" ()
      (:describes "drop the mark, the prompt and the pending chord")
    (setf (doc:mark (%of)) nil)
    (doc:forget-spans (%of))
    (if (prompt:askingp) (prompt:cancel) (log:note "quit")))
  (command:defcommand "recenter" ()
      (:describes "point to the middle of the window")
    (let ((win (window:focused)))
      (setf (window:scroll win)
            (max 0 (- (doc:at-line (%of)) (floor (window:lines win) 2))))))
  (command:defcommand "scroll-up" () (:describes "a screenful on")
    (let* ((win (window:focused)) (document (%of))
           (step (max 1 (- (window:lines win) 2))))
      (setf (window:scroll win)
            (min (max 0 (1- (doc:line-count document)))
                 (+ (window:scroll win) step)))
      (doc:goto document (+ (doc:at-line document) step) (doc:at-col document))))
  (command:defcommand "scroll-down" () (:describes "a screenful back")
    (let* ((win (window:focused)) (document (%of))
           (step (max 1 (- (window:lines win) 2))))
      (setf (window:scroll win) (max 0 (- (window:scroll win) step)))
      (doc:goto document (max 0 (- (doc:at-line document) step))
                (doc:at-col document)))))

(defun commands ()
  (%motion)
  (%editing))
