(defpackage #:pine.edit.commands
  (:use #:cl)
  (:local-nicknames (#:cmd #:pine/repl/command) (#:mode #:pine/repl/mode)
                    (#:node #:pine/fs/node) (#:buffer #:pine.edit.buffer)
                    (#:window #:pine.edit.window) (#:text #:pine.edit.text)
                    (#:key #:pine.edit.key) (#:render #:pine.edit.render)
                    (#:prompt #:pine.edit.prompt) (#:log #:pine/run/log)
                    (#:session #:pine/repl/session) (#:d #:pine/data))
  (:export #:commands #:*kill-ring* #:kill #:yank))

(in-package #:pine.edit.commands)

(defvar *kill-ring* nil)
(defvar *kill-kept* 60)
(defvar *evaluating* nil)

(defun kill (string)
  (push string *kill-ring*)
  (when (> (length *kill-ring*) *kill-kept*)
    (setf *kill-ring* (subseq *kill-ring* 0 *kill-kept*)))
  string)

(defun yank () (first *kill-ring*))

(defun %b () (buffer:current))

(defun %case-word (by)
  (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
    (multiple-value-bind (to-line to-col)
        (text:move-by :word (pine/data:held (buffer:lines b)) line col 1)
      (when (= line to-line)
        (let ((word (buffer:delete-region! b line col to-line to-col)))
          (buffer:insert! b (funcall by word)))))))

(defun %session ()
  (or *evaluating*
      (setf *evaluating*
            (session:open-session
             :name "editor"
             :package (or (find-package :pine.user) (find-package :cl-user))))))

(defun %as-path (typed) (prompt:expanded typed))

(defun commands ()
  (cmd:defcommand "forward-char" () (:describes "point one character on")
    (buffer:move! (%b) :char 1))
  (cmd:defcommand "backward-char" () (:describes "point one character back")
    (buffer:move! (%b) :char -1))
  (cmd:defcommand "forward-word" () (:describes "point one word on")
    (buffer:move! (%b) :word 1))
  (cmd:defcommand "backward-word" () (:describes "point one word back")
    (buffer:move! (%b) :word -1))
  (cmd:defcommand "next-line" () (:describes "point one line down")
    (buffer:move! (%b) :line 1))
  (cmd:defcommand "previous-line" () (:describes "point one line up")
    (buffer:move! (%b) :line -1))
  (cmd:defcommand "beginning-of-line" () (:describes "point to column zero")
    (buffer:goto! (%b) (buffer:point-line (%b)) 0))
  (cmd:defcommand "end-of-line" () (:describes "point to the end of the line")
    (buffer:goto! (%b) (buffer:point-line (%b))
                  (length (buffer:line (%b) (buffer:point-line (%b))))))
  (cmd:defcommand "beginning-of-buffer" () (:describes "point to the first line")
    (buffer:goto! (%b) 0 0))
  (cmd:defcommand "end-of-buffer" () (:describes "point to the last line")
    (buffer:move! (%b) :buffer 1))
  (cmd:defcommand "newline" () (:describes "break the line at point")
    (let ((b (%b)))
      (unless (mode:claimed b :newline)
        (buffer:newline! b))
      (buffer:point b)))
  (cmd:defcommand "indent-line" () (:describes "indent this line as the parse says")
    (buffer:indent-line! (%b) (buffer:point-line (%b))
                         (render:indent-for (%b) (buffer:point-line (%b)))))
  (cmd:defcommand "undo" () (:describes "put back what the last edit changed")
    (buffer:undo! (%b)))
  (cmd:defcommand "redo" () (:describes "do again what undo put back")
    (buffer:redo! (%b)))
  (cmd:defcommand "delete-backward-char" () (:describes "take the character before point")
    (buffer:delete-back! (%b)))
  (cmd:defcommand "set-mark" () (:describes "put the mark at point")
    (buffer:mark! (%b)))
  (cmd:defcommand "kill-region" ()
      (:describes "take the region and keep it")
    (let ((taken (buffer:region-of (%b))))
      (when taken
        (kill taken)
        (destructuring-bind (line col) (buffer:mark (%b))
          (multiple-value-bind (fresh at-line at-col)
              (text:delete (pine/data:held (buffer:lines (%b)))
                           line col
                           (buffer:point-line (%b)) (buffer:point-col (%b)))
            (pine/data:put! (buffer:lines (%b)) fresh)
            (buffer:goto! (%b) at-line at-col)
            (setf (buffer:mark (%b)) nil)
            (buffer:changed (%b)))))
      taken))
  (cmd:defcommand "copy-region" () (:describes "keep the region without taking it")
    (let ((taken (buffer:region-of (%b))))
      (when taken
        (kill taken)
        (setf (buffer:mark (%b)) nil))
      taken))
  (cmd:defcommand "yank" () (:describes "put back what was killed")
    (let ((held (yank)))
      (when held (buffer:insert! (%b) held))
      held))
  (cmd:defcommand "delete-char" () (:describes "take the character at point")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
      (if (< col (length (buffer:line b line)))
          (buffer:delete-region! b line col line (1+ col))
          (when (< (1+ line) (buffer:line-count b))
            (buffer:delete-region! b line col (1+ line) 0)))))
  (cmd:defcommand "kill-line" () (:describes "take the rest of the line and keep it")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b))
           (text (buffer:line b line)))
      (kill (if (< col (length text))
                (buffer:delete-region! b line col line (length text))
                (when (< (1+ line) (buffer:line-count b))
                  (buffer:delete-region! b line col (1+ line) 0))))))
  (cmd:defcommand "kill-word" () (:describes "take the word after point and keep it")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
      (multiple-value-bind (to-line to-col)
          (text:move-by :word (pine/data:held (buffer:lines b)) line col 1)
        (kill (buffer:delete-region! b line col to-line to-col)))))
  (cmd:defcommand "backward-kill-word" () (:describes "take the word before point and keep it")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
      (multiple-value-bind (from-line from-col)
          (text:move-by :word (pine/data:held (buffer:lines b)) line col -1)
        (kill (buffer:delete-region! b from-line from-col line col)))))
  (cmd:defcommand "open-line" () (:describes "a fresh line below, point where it is")
    (let ((b (%b)))
      (buffer:newline! b)
      (buffer:move! b :char -1)))
  (cmd:defcommand "transpose-chars" () (:describes "swap the two characters around point")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b))
           (text (buffer:line b line)))
      (when (and (plusp col) (<= col (length text)))
        (let ((taken (buffer:delete-region! b line (1- col) line col)))
          (buffer:goto! b line (min (length (buffer:line b line)) col))
          (buffer:insert! b taken)))))
  (cmd:defcommand "mark-whole-buffer" () (:describes "the region is everything")
    (let ((b (%b)))
      (buffer:mark! b 0 0)
      (buffer:move! b :buffer 1)))
  (cmd:defcommand "keyboard-quit" () (:describes "drop the mark, the prompt and the pending chord")
    (setf (buffer:mark (%b)) nil)
    (buffer:clear-properties! (%b))
    (if (prompt:asking-p) (prompt:cancel!) (log:note "quit")))
  (cmd:defcommand "goto-line" (line)
      (:describes "point to a line by number"
       :asks '((:prompt "Line: " :as :integer)))
    (let ((n (if (integerp line) line (parse-integer (princ-to-string line)
                                                     :junk-allowed t))))
      (when n (buffer:goto! (%b) (max 0 (1- n)) 0))))
  (cmd:defcommand "scroll-up" () (:describes "a screenful on")
    (let* ((w (window:focused)) (b (%b))
           (step (max 1 (- (window:height-of w) 2))))
      (setf (window:scroll-of w) (min (max 0 (1- (buffer:line-count b)))
                                      (+ (window:scroll-of w) step)))
      (buffer:goto! b (+ (buffer:point-line b) step) (buffer:point-col b))))
  (cmd:defcommand "scroll-down" () (:describes "a screenful back")
    (let* ((w (window:focused)) (b (%b))
           (step (max 1 (- (window:height-of w) 2))))
      (setf (window:scroll-of w) (max 0 (- (window:scroll-of w) step)))
      (buffer:goto! b (max 0 (- (buffer:point-line b) step)) (buffer:point-col b))))
  (cmd:defcommand "recenter" () (:describes "point to the middle of the window")
    (let ((w (window:focused)))
      (setf (window:scroll-of w)
            (max 0 (- (buffer:point-line (%b)) (floor (window:height-of w) 2))))))
  (cmd:defcommand "eval-expression" (form)
      (:describes "read a form and evaluate it"
       :asks '((:prompt "Eval: " :history :eval)))
    (let* ((s (%session))
           (e (session:evaluate s (session:read s (princ-to-string form)))))
      (if (session:fault e)
          (log:note "~a" (session:fault e))
          (log:note "~{~s~^, ~}" (session:answered e)))
      (first (session:answered e))))
  (cmd:defcommand "describe-command" (name)
      (:describes "what a command is for, and what it is bound to"
       :asks '((:prompt "Describe command: " :category :command :must-match t)))
    (let ((c (cmd:command-named name)))
      (when c
        (log:note "~a: ~a~@[  (~a)~]" (cmd:name c) (cmd:describes c)
                  (car (rassoc (cmd:name c) (key:bindings-of (%b)) :test #'equal)))
        (cmd:describes c))))
  (cmd:defcommand "find-file" (path)
      (:describes "open a file in a buffer"
       :asks (list (list :prompt "Find file: " :category :file :history :files)))
    (let ((path (%as-path (princ-to-string path))))
      (if (uiop:directory-exists-p path)
          (log:note "~a is a directory" path)
          (let* ((name (or (ignore-errors (file-namestring (pathname path))) path))
                 (b (or (buffer:buffer-named name) (buffer:make-buffer name))))
            (buffer:visit! b path)
      (setf (buffer:current) b)
            (let ((w (window:focused)))
              (when w (window:show! w b)))
            (node:full-name b)))))
  (cmd:defcommand "revert-buffer" () (:describes "the file again, as it is on disk"
                                     :asks '((:prompt "Revert from disk? "
                                              :must-match t)))
    (let ((b (%b)))
      (if (buffer:file-of b)
          (and (buffer:revert! b) (log:note "reverted ~a" (buffer:file-of b)) t)
          (log:note "~a has no file" (node:name b)))))
  (cmd:defcommand "save-buffer" () (:describes "write the buffer to its file")
    (let ((b (%b)))
      (if (buffer:file-of b)
          (buffer:save! b)
          (cmd:run "write-file"))))
  (cmd:defcommand "write-file" (path)
      (:describes "write the buffer to a file you name"
       :asks (list (list :prompt "Write file: " :category :file :history :files)))
    (let ((b (%b)))
      (setf (buffer:file-of b) (%as-path (princ-to-string path)))
      (buffer:save! b)
      (log:note "wrote ~a" (buffer:file-of b))
      (buffer:file-of b)))
  (cmd:defcommand "switch-to-buffer" (name)
      (:describes "show a buffer here, making it if there is none"
       :asks '((:prompt "Buffer: " :category :buffer)))
    (let* ((name (princ-to-string name))
           (b (or (buffer:buffer-named name) (buffer:make-buffer name))))
      (setf (buffer:current) b)
      (node:full-name b)))
  (cmd:defcommand "kill-buffer" (&optional name)
      (:describes "forget a buffer"
       :asks '((:prompt "Kill buffer: " :category :buffer :must-match t)))
    (let* ((name (princ-to-string (or name (node:name (%b)))))
           (gone (buffer:buffer-named name)))
      (when gone
        (pine.ts.parser:forget name)
        (buffer:kill-buffer name)
        (let ((instead (buffer:current)))
          (dolist (w (window:windows))
            (when (eq gone (window:buffer-of w))
              (window:show! w instead)))))
      (and gone t)))
  (cmd:defcommand "split-window-below" () (:describes "two windows, one above the other")
    (window:split! (window:focused) :below)
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "split-window-right" () (:describes "two windows, side by side")
    (window:split! (window:focused) :beside)
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "delete-window" () (:describes "close this window")
    (window:close! (window:focused))
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "delete-other-windows" () (:describes "this window alone")
    (window:only! (window:focused))
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "run-command" () (:describes "run a command by name")
    (prompt:ask "M-x " :category :command :must-match t :history :commands
                :then (lambda (name)
                        (let ((c (cmd:command-named name)))
                          (if c (cmd:run c) (log:note "no command named ~a" name))))))
  (cmd:defcommand "answer" () (:describes "accept what is typed at the prompt")
    (if (prompt:descends-p (prompt:asking))
        (prompt:descend!)
        (prompt:answer!)))
  (cmd:defcommand "history-previous" () (:describes "what was answered here before")
    (prompt:walk-history 1))
  (cmd:defcommand "history-next" () (:describes "the answer after that one")
    (prompt:walk-history -1))
  (cmd:defcommand "cancel" () (:describes "put the prompt away")
    (prompt:cancel!))
  (cmd:defcommand "complete" () (:describes "fill the prompt from the candidates")
    (prompt:complete!))
  (cmd:defcommand "next-candidate" () (:describes "the next candidate")
    (prompt:choose! 1))
  (cmd:defcommand "previous-candidate" () (:describes "the candidate before")
    (prompt:choose! -1))
  (cmd:defcommand "yank-pop" () (:describes "the kill before the one just put back")
    (let ((held (second *kill-ring*)))
      (when held
        (setf *kill-ring* (append (rest *kill-ring*) (list (first *kill-ring*))))
        (let ((b (%b)))
          (when (first *kill-ring*)
            (buffer:insert! b (first *kill-ring*)))))
      held))
  (cmd:defcommand "exchange-point-and-mark" () (:describes "point and mark swap places")
    (let* ((b (%b)) (mark (buffer:mark b)) (at (buffer:point b)))
      (when mark
        (buffer:mark! b (first at) (second at))
        (buffer:goto! b (first mark) (second mark)))))
  (cmd:defcommand "new-buffer" (name) (:describes "an empty buffer"
                                       :asks '((:prompt "Buffer name: ")))
    (let ((b (buffer:make-buffer (princ-to-string name))))
      (setf (buffer:current) b)
      (window:show! (window:focused) b)
      (node:full-name b)))
  (cmd:defcommand "indent-region" () (:describes "indent every line of the region")
    (let* ((b (%b)) (span (buffer:mark b)))
      (when span
        (loop :for line :from (min (first span) (buffer:point-line b))
                :to (max (first span) (buffer:point-line b))
              :do (buffer:indent-line! b line (render:indent-for b line))))))
  (cmd:defcommand "comment-line" () (:describes "comment this line, or uncomment it")
    (let* ((b (%b))
           (line (buffer:point-line b))
           (text (buffer:line b line))
           (mark (or (mode:setting (buffer:mode-of b) :comment) ";;"))
           (from (text:indent-width text))
           (body (subseq text from)))
      (buffer:goto! b line 0)
      (buffer:delete-region! b line 0 line (length text))
      (buffer:insert! b
                      (concatenate 'string (make-string from :initial-element #\Space)
                                   (if (and (>= (length body) (length mark))
                                            (string= mark body :end2 (length mark)))
                                       (string-left-trim " " (subseq body (length mark)))
                                       (concatenate 'string mark " " body))))))
  (cmd:defcommand "upcase-word" () (:describes "the word after point, in capitals")
    (%case-word #'string-upcase))
  (cmd:defcommand "downcase-word" () (:describes "the word after point, in small letters")
    (%case-word #'string-downcase))
  (cmd:defcommand "capitalize-word" () (:describes "the word after point, capitalised")
    (%case-word #'string-capitalize))
  (cmd:defcommand "enlarge-window" () (:describes "give this window more of the room")
    (let ((w (window:focused)))
      (setf (window:weight-of w) (min 16 (1+ (window:weight-of w))))))
  (cmd:defcommand "shrink-window" () (:describes "give this window less of the room")
    (let ((w (window:focused)))
      (setf (window:weight-of w) (max 1 (1- (window:weight-of w))))))
  (cmd:defcommand "balance-windows" () (:describes "every window the same size")
    (dolist (w (window:windows) t) (setf (window:weight-of w) 1)))
  (cmd:defcommand "other-window" () (:describes "move the keyboard to the next window")
    (let* ((all (window:windows))
           (at (or (position (window:focused) all) 0)))
      (window:focus! (nth (mod (1+ at) (length all)) all))
      (node:name (window:focused))))
  (cmd:defcommand "insert-tab" () (:describes "a tab's worth of spaces")
    (let* ((b (%b))
           (width (max 1 (or (buffer:setting b :tab-width) 8))))
      (buffer:insert! b (make-string width :initial-element #\Space))
      width))
  (cmd:defcommand "overwrite-mode" () (:describes "type over what is there")
    (let* ((b (%b))
           (on (not (member "overwrite" (buffer:minors-of b) :test #'equal))))
      (setf (buffer:minors-of b)
            (if on
                (adjoin "overwrite" (buffer:minors-of b) :test #'equal)
                (remove "overwrite" (buffer:minors-of b) :test #'equal)))
      (log:note "overwrite is ~:[off~;on~]" on)
      on))
  (cmd:defcommand "find-recent" () (:describes "a file opened here before")
    (let ((found (buffer:recent)))
      (if found
          (progn (prompt:ask "Recent: " :must-match t :candidates found
                             :then (lambda (said) (cmd:run "find-file" (list said))))
                 :asking)
          (log:note "nothing has been opened yet"))))
  (cmd:defcommand "format-buffer" () (:describes "indent every line of it")
    (let* ((b (%b))
           (n 0))
      (dotimes (line (buffer:line-count b))
        (let ((width (render:indent-for b line)))
          (when width
            (buffer:goto! b line 0)
            (cmd:run "indent-line")
            (incf n))))
      (log:note "indented ~d line~:p" n)
      n)))
