(defpackage #:pine.edit.commands
  (:use #:cl)
  (:local-nicknames (#:cmd #:pine.repl.command) (#:mode #:pine.repl.mode)
                    (#:node #:pine.fs.node) (#:buffer #:pine.edit.buffer)
                    (#:window #:pine.edit.window) (#:text #:pine.edit.text)
                    (#:key #:pine.edit.key) (#:render #:pine.edit.render)
                    (#:prompt #:pine.edit.prompt) (#:log #:pine.run.log)
                    (#:session #:pine.repl.session) (#:d #:pine.data))
  (:export #:install #:*kill-ring* #:kill #:yank))

(in-package #:pine.edit.commands)

(defvar *kill-ring* nil)
(defvar *kill-kept* 60)
(defvar *evaluating* nil)

(defun kill (string)
  (push string *kill-ring*)
  (when (> (length *kill-ring*) *kill-kept*)
    (setf *kill-ring* (subseq *kill-ring* 0 *kill-kept*)))
  string)

(defun yank () (first *kill-ring*))

(defun %b () (buffer:current))

(defun %session ()
  (or *evaluating*
      (setf *evaluating*
            (session:open-session
             :name "editor"
             :package (or (find-package :pine.user) (find-package :cl-user))))))

(defun %as-path (typed) (prompt:expanded typed))

(defun %commands ()
  (cmd:defcommand "forward-char" () (:describes "point one character on")
    (buffer:move! (%b) :char 1))
  (cmd:defcommand "backward-char" () (:describes "point one character back")
    (buffer:move! (%b) :char -1))
  (cmd:defcommand "forward-word" () (:describes "point one word on")
    (buffer:move! (%b) :word 1))
  (cmd:defcommand "backward-word" () (:describes "point one word back")
    (buffer:move! (%b) :word -1))
  (cmd:defcommand "next-line" () (:describes "point one line down")
    (buffer:move! (%b) :line 1))
  (cmd:defcommand "previous-line" () (:describes "point one line up")
    (buffer:move! (%b) :line -1))
  (cmd:defcommand "beginning-of-line" () (:describes "point to column zero")
    (buffer:goto! (%b) (buffer:point-line (%b)) 0))
  (cmd:defcommand "end-of-line" () (:describes "point to the end of the line")
    (buffer:goto! (%b) (buffer:point-line (%b))
                  (length (buffer:line (%b) (buffer:point-line (%b))))))
  (cmd:defcommand "beginning-of-buffer" () (:describes "point to the first line")
    (buffer:goto! (%b) 0 0))
  (cmd:defcommand "end-of-buffer" () (:describes "point to the last line")
    (buffer:move! (%b) :buffer 1))
  (cmd:defcommand "newline" () (:describes "break the line at point")
    (buffer:newline! (%b))
    (when (mode:setting (buffer:mode-of (%b)) :grammar)
      (buffer:indent-line! (%b) (buffer:point-line (%b))
                           (render:indent-for (%b) (buffer:point-line (%b)))))
    (buffer:point (%b)))
  (cmd:defcommand "indent-line" () (:describes "indent this line as the parse says")
    (buffer:indent-line! (%b) (buffer:point-line (%b))
                         (render:indent-for (%b) (buffer:point-line (%b)))))
  (cmd:defcommand "undo" () (:describes "put back what the last edit changed")
    (buffer:undo! (%b)))
  (cmd:defcommand "redo" () (:describes "do again what undo put back")
    (buffer:redo! (%b)))
  (cmd:defcommand "delete-backward-char" () (:describes "take the character before point")
    (buffer:delete-back! (%b)))
  (cmd:defcommand "set-mark" () (:describes "put the mark at point")
    (buffer:mark! (%b)))
  (cmd:defcommand "kill-region" () (:describes "take the region and keep it")
    (let ((taken (buffer:region-of (%b))))
      (when taken
        (kill taken)
        (destructuring-bind (line col) (buffer:mark (%b))
          (multiple-value-bind (fresh at-line at-col)
              (text:delete (pine.run.cell:held (buffer:lines (%b)))
                           line col
                           (buffer:point-line (%b)) (buffer:point-col (%b)))
            (pine.run.cell:put (buffer:lines (%b)) fresh)
            (buffer:goto! (%b) at-line at-col)
            (buffer:changed (%b)))))
      taken))
  (cmd:defcommand "copy-region" () (:describes "keep the region without taking it")
    (let ((taken (buffer:region-of (%b))))
      (when taken (kill taken))
      taken))
  (cmd:defcommand "yank" () (:describes "put back what was killed")
    (let ((held (yank)))
      (when held (buffer:insert! (%b) held))
      held))
  (cmd:defcommand "delete-char" () (:describes "take the character at point")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
      (if (< col (length (buffer:line b line)))
          (buffer:delete-region! b line col line (1+ col))
          (when (< (1+ line) (buffer:line-count b))
            (buffer:delete-region! b line col (1+ line) 0)))))
  (cmd:defcommand "kill-line" () (:describes "take the rest of the line and keep it")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b))
           (text (buffer:line b line)))
      (kill (if (< col (length text))
                (buffer:delete-region! b line col line (length text))
                (when (< (1+ line) (buffer:line-count b))
                  (buffer:delete-region! b line col (1+ line) 0))))))
  (cmd:defcommand "kill-word" () (:describes "take the word after point and keep it")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
      (multiple-value-bind (to-line to-col)
          (text:move-by :word (pine.run.cell:held (buffer:lines b)) line col 1)
        (kill (buffer:delete-region! b line col to-line to-col)))))
  (cmd:defcommand "backward-kill-word" () (:describes "take the word before point and keep it")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b)))
      (multiple-value-bind (from-line from-col)
          (text:move-by :word (pine.run.cell:held (buffer:lines b)) line col -1)
        (kill (buffer:delete-region! b from-line from-col line col)))))
  (cmd:defcommand "open-line" () (:describes "a fresh line below, point where it is")
    (let ((b (%b)))
      (buffer:newline! b)
      (buffer:move! b :char -1)))
  (cmd:defcommand "transpose-chars" () (:describes "swap the two characters around point")
    (let* ((b (%b)) (line (buffer:point-line b)) (col (buffer:point-col b))
           (text (buffer:line b line)))
      (when (and (plusp col) (<= col (length text)))
        (let ((taken (buffer:delete-region! b line (1- col) line col)))
          (buffer:goto! b line (min (length (buffer:line b line)) col))
          (buffer:insert! b taken)))))
  (cmd:defcommand "mark-whole-buffer" () (:describes "the region is everything")
    (let ((b (%b)))
      (buffer:mark! b 0 0)
      (buffer:move! b :buffer 1)))
  (cmd:defcommand "keyboard-quit" () (:describes "drop the mark, the prompt and the pending chord")
    (setf (buffer:mark (%b)) nil)
    (buffer:clear-properties! (%b))
    (if (prompt:asking-p) (prompt:cancel!) (log:note "quit")))
  (cmd:defcommand "goto-line" (line)
      (:describes "point to a line by number"
       :asks '((:prompt "Line: " :as :integer)))
    (let ((n (if (integerp line) line (parse-integer (princ-to-string line)
                                                     :junk-allowed t))))
      (when n (buffer:goto! (%b) (max 0 (1- n)) 0))))
  (cmd:defcommand "scroll-up" () (:describes "a screenful on")
    (let* ((w (window:focused)) (b (%b))
           (step (max 1 (- (window:height-of w) 2))))
      (setf (window:scroll-of w) (min (max 0 (1- (buffer:line-count b)))
                                      (+ (window:scroll-of w) step)))
      (buffer:goto! b (+ (buffer:point-line b) step) (buffer:point-col b))))
  (cmd:defcommand "scroll-down" () (:describes "a screenful back")
    (let* ((w (window:focused)) (b (%b))
           (step (max 1 (- (window:height-of w) 2))))
      (setf (window:scroll-of w) (max 0 (- (window:scroll-of w) step)))
      (buffer:goto! b (max 0 (- (buffer:point-line b) step)) (buffer:point-col b))))
  (cmd:defcommand "recenter" () (:describes "point to the middle of the window")
    (let ((w (window:focused)))
      (setf (window:scroll-of w)
            (max 0 (- (buffer:point-line (%b)) (floor (window:height-of w) 2))))))
  (cmd:defcommand "eval-expression" (form)
      (:describes "read a form and evaluate it"
       :asks '((:prompt "Eval: " :history :eval)))
    (let* ((s (%session))
           (e (session:evaluate s (session:read s (princ-to-string form)))))
      (if (session:fault e)
          (log:note "~a" (session:fault e))
          (log:note "~{~s~^, ~}" (session:answered e)))
      (first (session:answered e))))
  (cmd:defcommand "describe-command" (name)
      (:describes "what a command is for, and what it is bound to"
       :asks '((:prompt "Describe command: " :category :command :must-match t)))
    (let ((c (cmd:command-named name)))
      (when c
        (log:note "~a: ~a~@[  (~a)~]" (cmd:name c) (cmd:describes c)
                  (car (rassoc (cmd:name c) (key:bindings-of (%b)) :test #'equal)))
        (cmd:describes c))))
  (cmd:defcommand "find-file" (path)
      (:describes "open a file in a buffer"
       :asks (list (list :prompt "Find file: " :category :file :history :files)))
    (let* ((path (%as-path (princ-to-string path)))
           (name (file-namestring (pathname path)))
           (b (or (buffer:buffer-named name) (buffer:make-buffer name))))
      (buffer:visit! b path)
      (setf (buffer:current) b)
      (let ((w (window:focused)))
        (when w (window:show! w b)))
      (node:full-name b)))
  (cmd:defcommand "save-buffer" () (:describes "write the buffer to its file")
    (buffer:save! (%b)))
  (cmd:defcommand "switch-to-buffer" (name)
      (:describes "show a buffer here"
       :asks '((:prompt "Buffer: " :category :buffer :must-match t)))
    (let ((b (buffer:buffer-named name)))
      (when b
        (setf (buffer:current) b)
        (window:show! (window:focused) b)
        (node:full-name b))))
  (cmd:defcommand "list-buffers" () (:describes "every buffer there is")
    (mapcar #'node:name (buffer:buffers)))
  (cmd:defcommand "kill-buffer" (name)
      (:describes "forget a buffer"
       :asks '((:prompt "Kill buffer: " :category :buffer :must-match t)))
    (pine.ts.parser:forget (princ-to-string name))
    (and (buffer:kill-buffer name) t))
  (cmd:defcommand "split-window-below" () (:describes "two windows, one above the other")
    (window:split! (window:focused) :below)
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "split-window-right" () (:describes "two windows, side by side")
    (window:split! (window:focused) :beside)
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "delete-window" () (:describes "close this window")
    (window:close! (window:focused))
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "delete-other-windows" () (:describes "this window alone")
    (window:only! (window:focused))
    (mapcar #'node:name (window:windows)))
  (cmd:defcommand "run-command" () (:describes "run a command by name")
    (prompt:ask "M-x " :category :command :must-match t :history :commands
                :then (lambda (name)
                        (let ((c (cmd:command-named name)))
                          (if c (cmd:run c) (log:note "no command named ~a" name))))))
  (cmd:defcommand "answer" () (:describes "accept what is typed at the prompt")
    (if (prompt:descends-p (prompt:asking))
        (prompt:descend!)
        (prompt:answer!)))
  (cmd:defcommand "history-previous" () (:describes "what was answered here before")
    (prompt:walk-history 1))
  (cmd:defcommand "history-next" () (:describes "the answer after that one")
    (prompt:walk-history -1))
  (cmd:defcommand "cancel" () (:describes "put the prompt away")
    (prompt:cancel!))
  (cmd:defcommand "complete" () (:describes "fill the prompt from the candidates")
    (prompt:complete!))
  (cmd:defcommand "next-candidate" () (:describes "the next candidate")
    (prompt:choose! 1))
  (cmd:defcommand "previous-candidate" () (:describes "the candidate before")
    (prompt:choose! -1))
  (cmd:defcommand "isearch-forward" () (:describes "search as you type")
    (let ((from (buffer:point (%b)))
          (b (%b)))
      (prompt:ask "I-search: "
                  :then (lambda (needle)
                          (multiple-value-bind (line col)
                              (text:search (pine.run.cell:held (buffer:lines b))
                                           needle (first from) (second from))
                            (if line
                                (progn (buffer:goto! b line col)
                                       (buffer:propertize! b line col
                                                           (+ col (length needle))
                                                           '(:face :match)))
                                (log:note "not found: ~a" needle)))))))
  (cmd:defcommand "other-window" () (:describes "move the keyboard to the next window")
    (let* ((all (window:windows))
           (at (or (position (window:focused) all) 0)))
      (window:focus! (nth (mod (1+ at) (length all)) all))
      (node:name (window:focused)))))

(defun %sources ()
  (prompt:source :command
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (c) (cons (cmd:name c) (cmd:describes c)))
                           (cmd:commands))))
  (prompt:source :buffer
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (b) (cons (node:name b) (or (buffer:file-of b) "")))
                           (buffer:buffers))))
  (prompt:source :mode
                 (lambda (typed) (declare (ignore typed))
                   (mapcar #'mode:name (mode:modes))))
  (prompt:source :file (lambda (typed) (prompt:files typed))))

(defun %modes ()
  (mode:mode "fundamental" :settings '(:indicator "Fund"))
  (mode:mode "text" :settings '(:tab-width 8 :indicator "Text"))
  (mode:mode "prog" :parent "text" :settings '(:indent 2 :comment ";"))
  (mode:mode "lisp" :parent "prog"
                    :settings '(:indicator "Lisp" :grammar :commonlisp)
                    :claims '((:files "*.lisp" "*.asd" "*.cl")))
  (mode:mode "pine" :parent "lisp"
                    :settings '(:indicator "Pine" :grammar :pine)
                    :claims '((:paths "*/pine/*.lisp")))
  (mode:minor "prompt" :precedence 20))

(defun %keys ()
  (dolist (pair '(("C-f" . "forward-char") ("C-b" . "backward-char")
                  ("M-f" . "forward-word") ("M-b" . "backward-word")
                  ("C-n" . "next-line")    ("C-p" . "previous-line")
                  ("C-a" . "beginning-of-line") ("C-e" . "end-of-line")
                  ("M-<" . "beginning-of-buffer") ("M->" . "end-of-buffer")
                  ("RET" . "newline") ("DEL" . "delete-backward-char")
                  ("C-SPC" . "set-mark") ("C-w" . "kill-region")
                  ("M-w" . "copy-region")
                  ("C-y" . "yank") ("C-/" . "undo") ("C-?" . "redo")
                  ("TAB" . "indent-line")
                  ("C-d" . "delete-char") ("C-k" . "kill-line")
                  ("M-d" . "kill-word") ("M-DEL" . "backward-kill-word")
                  ("C-o" . "open-line") ("C-t" . "transpose-chars")
                  ("C-l" . "recenter") ("C-v" . "scroll-up") ("M-v" . "scroll-down")
                  ("C-g" . "keyboard-quit")
                  ("M-:" . "eval-expression")
                  ("M-g g" . "goto-line")
                  ("C-h f" . "describe-command")
                  ("C-x C-f" . "find-file") ("C-x C-s" . "save-buffer")
                  ("C-x b" . "switch-to-buffer") ("C-x k" . "kill-buffer")
                  ("C-x C-b" . "list-buffers") ("C-x h" . "mark-whole-buffer")
                  ("C-x 2" . "split-window-below")
                  ("C-x 3" . "split-window-right")
                  ("C-x 0" . "delete-window")
                  ("C-x 1" . "delete-other-windows")
                  ("C-x o" . "other-window")))
    (mode:bind "text" (car pair) (cdr pair)))
  (mode:bind "text" "M-x" "run-command")
  (mode:bind "text" "C-s" "isearch-forward")
  (dolist (pair '(("RET" . "answer") ("C-g" . "cancel") ("TAB" . "complete")
                  ("Return" . "answer") ("Escape" . "cancel") ("Tab" . "complete")
                  ("C-n" . "next-candidate") ("C-p" . "previous-candidate")
                  ("Down" . "next-candidate") ("Up" . "previous-candidate")
                  ("M-p" . "history-previous") ("M-n" . "history-next")))
    (mode:bind "prompt" (car pair) (cdr pair))))

(defun %asking (c)
  (let* ((spec (first (cmd:asks c)))
         (initial (getf spec :initial)))
    (prompt:ask (or (getf spec :prompt) (format nil "~a: " (cmd:name c)))
                :category (getf spec :category)
                :history (getf spec :history)
                :must-match (getf spec :must-match)
                :initial (if (functionp initial) (funcall initial) initial)
                :then (lambda (answer) (cmd:run c (list answer))))
    :asking))

(defun %confirming (question thunk)
  (prompt:ask (format nil "~a " question)
              :candidates (list "yes" "no") :must-match t
              :then (lambda (said) (when (equal "yes" said) (funcall thunk))))
  :asking)

(defun install ()
  (setf pine.ui.build:*asking* #'%confirming)
  (%modes)
  (%commands)
  (%sources)
  (%keys)
  (setf cmd:*asking* #'%asking)
  t)
