(defpackage #:pine.edit.defaults
  (:use #:cl)
  (:local-nicknames (#:cmd #:pine.repl.command) (#:mode #:pine.repl.mode)
                    (#:node #:pine.fs.node) (#:buffer #:pine.edit.buffer)
                    (#:prompt #:pine.edit.prompt) (#:edit #:pine.edit.commands)
                    (#:listing #:pine.edit.listing))
  (:export #:install))

(in-package #:pine.edit.defaults)

(defparameter +settings+
  '((:tab-width      . "how wide a tab is drawn")
    (:indent         . "how far a body indents")
    (:comment        . "what starts a comment on a line")
    (:grammar        . "which language the parse follows")
    (:indicator      . "what the modeline calls this mode")
    (:format-on-save . "whether saving reindents first")))

(defun %files (typed) (prompt:files typed))

(defun %sources ()
  (prompt:source :command
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (c) (cons (cmd:name c) (cmd:describes c)))
                           (cmd:commands))))
  (prompt:source :buffer
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (b) (cons (node:name b) (or (buffer:file-of b) "")))
                           (buffer:buffers))))
  (prompt:source :mode
                 (lambda (typed) (declare (ignore typed))
                   (mapcar #'mode:name (mode:modes))))
  (prompt:source :file (lambda (typed) (prompt:files typed))))

(defun %indenting (b &rest arguments)
  (declare (ignore arguments))
  (buffer:newline! b)
  (buffer:indent-line! b (buffer:point-line b)
                       (pine.edit.render:indent-for b (buffer:point-line b)))
  :indented)

(defun %overwriting (b said)
  (let ((line (buffer:point-line b)) (col (buffer:point-col b)))
    (when (< col (length (buffer:line b line)))
      (buffer:delete-region! b line col line (min (length (buffer:line b line))
                                                  (+ col (length said))))))
  nil)

(defun %modes ()
  (mode:mode "fundamental" :settings '(:indicator "Fund"))
  (mode:mode "text" :settings '(:tab-width 8 :indicator "Text"))
  (mode:mode "prog" :parent "text" :settings '(:indent 2 :comment ";"))
  (mode:mode "lisp" :parent "prog"
                    :settings '(:indicator "Lisp" :grammar :commonlisp)
                    :claims '((:files "*.lisp" "*.asd" "*.cl")))
  (mode:mode "pine" :parent "lisp"
                    :settings '(:indicator "Pine" :grammar :pine)
                    :claims '((:paths "*/pine/*.lisp")))
  (mode:minor "prompt" :precedence 20)
  (mode:minor "overwrite" :precedence 10 :settings '(:indicator "Ovwrt"))
  (mode:minor "list" :precedence 15)
  (mode:bind "list" "RET" "list-activate")
  (mode:bind "list" "Return" "list-activate")
  (mode:bind "list" "n" "list-next")
  (mode:bind "list" "p" "list-prev")
  (mode:bind "list" "C-n" "list-next")
  (mode:bind "list" "C-p" "list-prev")
  (mode:bind "list" "Down" "list-next")
  (mode:bind "list" "Up" "list-prev")
  (mode:handle "prog" :newline #'%indenting)
  (mode:handle "overwrite" :insert #'%overwriting))

(defun %keys ()
  (dolist (pair '(("C-f" . "forward-char") ("C-b" . "backward-char")
                  ("Right" . "forward-char") ("Left" . "backward-char")
                  ("M-f" . "forward-word") ("M-b" . "backward-word")
                  ("C-n" . "next-line")    ("C-p" . "previous-line")
                  ("Down" . "next-line")   ("Up" . "previous-line")
                  ("Home" . "beginning-of-line") ("End" . "end-of-line")
                  ("Prior" . "scroll-down") ("Next" . "scroll-up")
                  ("PageUp" . "scroll-down") ("PageDown" . "scroll-up")
                  ("Return" . "newline") ("BackSpace" . "delete-backward-char")
                  ("Delete" . "delete-char") ("Escape" . "keyboard-quit")
                  ("Tab" . "indent-line")
                  ("M-y" . "yank-pop") ("C-r" . "isearch-backward")
                  ("M-g g" . "goto-line") ("C-x C-b" . "list-buffers")
                  ("C-x n" . "new-buffer") ("C-x t" . "terminal")
                  ("C-M-\\" . "indent-region")
                  ("M-;" . "comment-line") ("C-x C-x" . "exchange-point-and-mark")
                  ("M-u" . "upcase-word") ("M-l" . "downcase-word")
                  ("M-c" . "capitalize-word")
                  ("C-h k" . "describe-key") ("C-h b" . "describe-bindings")
                  ("C-h m" . "describe-mode") ("C-h c" . "describe-command")
                  ("C-h v" . "describe-variables")
                  ("C-a" . "beginning-of-line") ("C-e" . "end-of-line")
                  ("M-<" . "beginning-of-buffer") ("M->" . "end-of-buffer")
                  ("RET" . "newline") ("DEL" . "delete-backward-char")
                  ("C-SPC" . "set-mark") ("C-w" . "kill-region")
                  ("M-w" . "copy-region")
                  ("C-y" . "yank") ("C-/" . "undo") ("C-?" . "redo")
                  ("TAB" . "indent-line")
                  ("C-d" . "delete-char") ("C-k" . "kill-line")
                  ("M-d" . "kill-word") ("M-DEL" . "backward-kill-word")
                  ("C-o" . "open-line") ("C-t" . "transpose-chars")
                  ("C-l" . "recenter") ("C-v" . "scroll-up") ("M-v" . "scroll-down")
                  ("C-g" . "keyboard-quit")
                  ("M-:" . "eval-expression")
                  ("M-g g" . "goto-line")
                  ("C-h f" . "describe-command")
                  ("C-x C-f" . "find-file") ("C-x C-s" . "save-buffer")
                  ("C-x b" . "switch-to-buffer") ("C-x k" . "kill-buffer")
                  ("C-x C-b" . "list-buffers") ("C-x h" . "mark-whole-buffer")
                  ("C-x 2" . "split-window-below")
                  ("C-x 3" . "split-window-right")
                  ("C-x 0" . "delete-window")
                  ("C-x 1" . "delete-other-windows")
                  ("C-x o" . "other-window")
                  ("C-x ^" . "enlarge-window") ("C-x -" . "shrink-window")
                  ("C-x +" . "balance-windows")))
    (mode:bind "text" (car pair) (cdr pair)))
  (mode:bind "text" "M-x" "run-command")
  (dolist (pair '(("C-x C-r" . "find-recent") ("M-o" . "overwrite-mode")
                  ("C-x j" . "jobs")))
    (mode:bind "text" (car pair) (cdr pair)))
  (dolist (pair '(("C-c C-l" . "load-file") ("C-c C-t" . "set-eval-target")
                  ("C-c TAB" . "format-buffer")))
    (mode:bind "prog" (car pair) (cdr pair)))
  (dolist (pair '(("RET" . "answer") ("C-g" . "cancel") ("TAB" . "complete")
                  ("Return" . "answer") ("Escape" . "cancel") ("Tab" . "complete")
                  ("C-n" . "next-candidate") ("C-p" . "previous-candidate")
                  ("Down" . "next-candidate") ("Up" . "previous-candidate")
                  ("M-p" . "history-previous") ("M-n" . "history-next")))
    (mode:bind "prompt" (car pair) (cdr pair))))

(defun %asking (c)
  (let* ((spec (first (cmd:asks c)))
         (initial (getf spec :initial)))
    (prompt:ask (or (getf spec :prompt) (format nil "~a: " (cmd:name c)))
                :category (getf spec :category)
                :history (getf spec :history)
                :must-match (getf spec :must-match)
                :initial (if (functionp initial) (funcall initial) initial)
                :then (lambda (answer) (cmd:run c (list answer))))
    :asking))

(defun %confirming (question thunk)
  (prompt:ask (format nil "~a " question)
              :candidates (list "yes" "no") :must-match t
              :then (lambda (said) (when (equal "yes" said) (funcall thunk))))
  :asking)

(defun %editing (question had write-back)
  (prompt:ask question :initial (princ-to-string (or had ""))
                       :then (lambda (said) (funcall write-back said)))
  :asking)

(defun %settings ()
  (cmd:defcommand "set-local" (key value)
      (:describes "a setting, for this buffer only"
       :asks '((:prompt "Setting: " :category :setting :must-match t)))
    (let ((key (if (keywordp key)
                   key
                   (intern (string-upcase (princ-to-string key)) :keyword))))
      (prompt:ask (format nil "~(~a~) here: " key)
                  :then (lambda (said)
                          (setf (buffer:setting (buffer:current) key)
                                (let ((*package* (find-package :keyword)))
                                  (handler-case (read-from-string said)
                                    (error () said))))))
      :asking))
  (cmd:defcommand "describe-variables" () (:describes "every setting, and what this buffer reads")
    (let ((b (buffer:current)))
      (listing:into "*help*"
                    (cons (format nil "settings in ~a" (node:name b))
                          (cons ""
                                (loop :for (key . says) :in +settings+
                                      :collect (format nil "~(~16a~) ~12a ~a" key
                                                       (or (buffer:setting b key) "")
                                                       says)))))))
  (prompt:source :setting
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (each)
                             (cons (string-downcase (string (car each))) (cdr each)))
                           +settings+))))

(defun %password (ssid then)
  (prompt:ask (format nil "Password for ~a: " ssid) :then then)
  :asking)

(defun install ()
  (setf pine.ui.build:*asking* #'%confirming
        pine.ui.build:*editing* #'%editing
        pine.provider.net:*asking* #'%password)
  (%modes)
  (edit:commands)
  (%sources)
  (%settings)
  (%keys)
  (setf cmd:*asking* #'%asking)
  t)
