(defpackage #:pine.edit.defaults
  (:use #:cl)
  (:local-nicknames (#:cmd #:pine.repl.command) (#:mode #:pine.repl.mode)
                    (#:node #:pine.fs.node) (#:buffer #:pine.edit.buffer)
                    (#:prompt #:pine.edit.prompt) (#:edit #:pine.edit.commands))
  (:export #:install))

(in-package #:pine.edit.defaults)

(defun %files (typed) (prompt:files typed))

(defun %sources ()
  (prompt:source :command
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (c) (cons (cmd:name c) (cmd:describes c)))
                           (cmd:commands))))
  (prompt:source :buffer
                 (lambda (typed) (declare (ignore typed))
                   (mapcar (lambda (b) (cons (node:name b) (or (buffer:file-of b) "")))
                           (buffer:buffers))))
  (prompt:source :mode
                 (lambda (typed) (declare (ignore typed))
                   (mapcar #'mode:name (mode:modes))))
  (prompt:source :file (lambda (typed) (prompt:files typed))))

(defun %modes ()
  (mode:mode "fundamental" :settings '(:indicator "Fund"))
  (mode:mode "text" :settings '(:tab-width 8 :indicator "Text"))
  (mode:mode "prog" :parent "text" :settings '(:indent 2 :comment ";"))
  (mode:mode "lisp" :parent "prog"
                    :settings '(:indicator "Lisp" :grammar :commonlisp)
                    :claims '((:files "*.lisp" "*.asd" "*.cl")))
  (mode:mode "pine" :parent "lisp"
                    :settings '(:indicator "Pine" :grammar :pine)
                    :claims '((:paths "*/pine/*.lisp")))
  (mode:minor "prompt" :precedence 20))

(defun %keys ()
  (dolist (pair '(("C-f" . "forward-char") ("C-b" . "backward-char")
                  ("Right" . "forward-char") ("Left" . "backward-char")
                  ("M-f" . "forward-word") ("M-b" . "backward-word")
                  ("C-n" . "next-line")    ("C-p" . "previous-line")
                  ("Down" . "next-line")   ("Up" . "previous-line")
                  ("Home" . "beginning-of-line") ("End" . "end-of-line")
                  ("Prior" . "scroll-down") ("Next" . "scroll-up")
                  ("PageUp" . "scroll-down") ("PageDown" . "scroll-up")
                  ("Return" . "newline") ("BackSpace" . "delete-backward-char")
                  ("Delete" . "delete-char") ("Escape" . "keyboard-quit")
                  ("Tab" . "indent-line")
                  ("M-y" . "yank-pop") ("C-r" . "isearch-backward")
                  ("M-g g" . "goto-line") ("C-x C-b" . "list-buffers")
                  ("C-x n" . "new-buffer") ("C-x t" . "terminal")
                  ("C-M-\\" . "indent-region")
                  ("M-;" . "comment-line") ("C-x C-x" . "exchange-point-and-mark")
                  ("M-u" . "upcase-word") ("M-l" . "downcase-word")
                  ("M-c" . "capitalize-word")
                  ("C-h k" . "describe-key") ("C-h b" . "describe-bindings")
                  ("C-h m" . "describe-mode") ("C-h c" . "describe-command")
                  ("C-a" . "beginning-of-line") ("C-e" . "end-of-line")
                  ("M-<" . "beginning-of-buffer") ("M->" . "end-of-buffer")
                  ("RET" . "newline") ("DEL" . "delete-backward-char")
                  ("C-SPC" . "set-mark") ("C-w" . "kill-region")
                  ("M-w" . "copy-region")
                  ("C-y" . "yank") ("C-/" . "undo") ("C-?" . "redo")
                  ("TAB" . "indent-line")
                  ("C-d" . "delete-char") ("C-k" . "kill-line")
                  ("M-d" . "kill-word") ("M-DEL" . "backward-kill-word")
                  ("C-o" . "open-line") ("C-t" . "transpose-chars")
                  ("C-l" . "recenter") ("C-v" . "scroll-up") ("M-v" . "scroll-down")
                  ("C-g" . "keyboard-quit")
                  ("M-:" . "eval-expression")
                  ("M-g g" . "goto-line")
                  ("C-h f" . "describe-command")
                  ("C-x C-f" . "find-file") ("C-x C-s" . "save-buffer")
                  ("C-x b" . "switch-to-buffer") ("C-x k" . "kill-buffer")
                  ("C-x C-b" . "list-buffers") ("C-x h" . "mark-whole-buffer")
                  ("C-x 2" . "split-window-below")
                  ("C-x 3" . "split-window-right")
                  ("C-x 0" . "delete-window")
                  ("C-x 1" . "delete-other-windows")
                  ("C-x o" . "other-window")))
    (mode:bind "text" (car pair) (cdr pair)))
  (mode:bind "text" "M-x" "run-command")
  (mode:bind "text" "C-s" "isearch-forward")
  (dolist (pair '(("RET" . "answer") ("C-g" . "cancel") ("TAB" . "complete")
                  ("Return" . "answer") ("Escape" . "cancel") ("Tab" . "complete")
                  ("C-n" . "next-candidate") ("C-p" . "previous-candidate")
                  ("Down" . "next-candidate") ("Up" . "previous-candidate")
                  ("M-p" . "history-previous") ("M-n" . "history-next")))
    (mode:bind "prompt" (car pair) (cdr pair))))

(defun %asking (c)
  (let* ((spec (first (cmd:asks c)))
         (initial (getf spec :initial)))
    (prompt:ask (or (getf spec :prompt) (format nil "~a: " (cmd:name c)))
                :category (getf spec :category)
                :history (getf spec :history)
                :must-match (getf spec :must-match)
                :initial (if (functionp initial) (funcall initial) initial)
                :then (lambda (answer) (cmd:run c (list answer))))
    :asking))

(defun %confirming (question thunk)
  (prompt:ask (format nil "~a " question)
              :candidates (list "yes" "no") :must-match t
              :then (lambda (said) (when (equal "yes" said) (funcall thunk))))
  :asking)

(defun install ()
  (setf pine.ui.build:*asking* #'%confirming)
  (%modes)
  (edit:commands)
  (%sources)
  (%keys)
  (setf cmd:*asking* #'%asking)
  t)
