;;;; wlr-layer-shell bindings, generated by the wayflan scanner from the
;;;; protocol XML shipped by the wlr-protocols guix package (in the manifest).
;;;; The XML path is resolved at compile time from GUIX_ENVIRONMENT, so the
;;;; build must run inside `guix shell -m manifest.scm'. This is the anchored
;;;; bar/panel surface protocol that gtk4-layer-shell wraps for the GTK app --
;;;; here we bind it directly, no C shim. The package uses the xdg-shell package
;;;; so the get_popup request's xdg_popup argument resolves.

(defpackage #:pine.wlr-layer-shell
  (:use #:cl #:wayflan-client #:wayflan-client.xdg-shell)
  (:documentation "zwlr_layer_shell_v1 / zwlr_layer_surface_v1 client bindings."))
(in-package #:pine.wlr-layer-shell)

(xyz.shunter.wayflan.client.scanner:wl-include
  (merge-pathnames "share/wlr-protocols/unstable/wlr-layer-shell-unstable-v1.xml"
                   (uiop:ensure-directory-pathname
                    (or (uiop:getenv "GUIX_ENVIRONMENT")
                        (error "GUIX_ENVIRONMENT unset: build inside guix shell -m manifest.scm"))))
  :export t)
