;;;; river window management bindings, generated by the wayflan scanner from
;;;; the protocol XML shipped by the river guix package (in the manifest).
;;;; The XML path is resolved at compile time from GUIX_ENVIRONMENT, so the
;;;; build must run inside `guix shell -m manifest.scm'. Two protocols: the
;;;; window management state machine (manage/render sequences, windows,
;;;; outputs, seats, nodes, shell surfaces) and the compositor-side keyboard
;;;; bindings that feed it. design/wm.org is the contract.

(defpackage #:pine.river-wm
  (:use #:cl #:wayflan-client)
  (:documentation "river_window_manager_v1 client bindings: windows, outputs,
seats, render nodes, decorations, shell surfaces."))
(in-package #:pine.river-wm)

(xyz.shunter.wayflan.client.scanner:wl-include
  (merge-pathnames "share/river-protocols/stable/river-window-management-v1.xml"
                   (uiop:ensure-directory-pathname
                    (or (uiop:getenv "GUIX_ENVIRONMENT")
                        (error "GUIX_ENVIRONMENT unset: build inside guix shell -m manifest.scm"))))
  :export t)

