(in-package #:pine/ui)

(defun %covers (w line col)
  (and (<= (top w) line) (< line (bottom w))
       (<= (left w) col) (< col (right w))))

(defgeneric under (widget line col)
  (:method ((w widget) line col)
    (let ((found nil))
      (dolist (part (parts w) found)
        (let ((it (under part line col)))
          (when it (setf found it))))))
  (:method ((w action) line col)
    (when (%covers w line col) (or (call-next-method) w)))
  (:method ((w choice) line col)
    (when (%covers w line col) (or (call-next-method) w)))
  (:method ((w slider) line col) (when (%covers w line col) w))
  (:method ((w scroll) line col) (when (%covers w line col) (call-next-method)))
  (:method ((w label) line col)
    (when (and (on-change w) (%covers w line col)) w)))

(defun value-at (w col)
  (let* ((n (max 1 (width w)))
         (rel (max 0 (min n (- col (left w)))))
         (span (- (high w) (low w))))
    (+ (low w) (round (* (/ rel n) span)))))

(defgeneric clicked (widget col)
  (:method ((w widget) col) (declare (ignore col)) nil)
  (:method ((w action) col) (declare (ignore col)) (on-click w))
  (:method ((w choice) col) (declare (ignore col)) (on-click w))
  (:method ((w slider) col)
    (let ((fn (on-change w)) (v (value-at w col)))
      (when fn (lambda () (funcall fn v))))))

(defun clicked-at (root line col)
  (let ((hit (under root line col)))
    (and hit (clicked hit col))))
