(in-package #:pine/ui)

(defclass styling (fs:value) ())

(defmethod fs:persistent-p ((n styling)) nil)

(defun css-color (role) (color role))

(defun css-glass (role &optional (a (metric :opacity 0.4)))
  (let ((rgb (unhex (color role))))
    (format nil "rgba(~d, ~d, ~d, ~a)" (first rgb) (second rgb) (third rgb) a)))

(defun css-rad () (format nil "~apx" (metric :radius 8)))

(defun css-mono () (format nil "~s, monospace" (metric :font "Maple Mono NF")))

(defgeneric selector (it)
  (:method ((it string)) it)
  (:method ((it symbol)) (format nil ".~(~a~)" (symbol-name it)))
  (:method ((it cons)) (format nil "~{.~(~a~)~}" (mapcar #'symbol-name it))))

(defun %compound (s &optional (from 0))
  (and (find-if (lambda (c) (member c '(#\Space #\, #\: #\.))) s :start from) t))

(defun %path-segment (sel)
  (let ((s (selector sel)))
    (if (and (plusp (length s)) (char= #\. (char s 0)) (not (%compound s 1)))
        (subseq s 1)
        s)))

(defun %selector (segment)
  (if (%compound segment) segment (format nil ".~a" segment)))

(defun styles ()
  (let ((at (fs:at "/ui/style"))
        (acc nil))
    (when at
      (dolist (each (fs:children at))
        (let ((props (fs:contents each)))
          (when (consp props)
            (push (list (%selector (fs:name each)) props) acc)))))
    (sort acc #'string< :key #'first)))

(defun style (selector properties)
  (first (put-rules (list (list selector properties)))))

(defun put-rules (pairs)
  (dolist (each pairs)
    (let ((n (fs:mount (make-instance 'styling)
                       (format nil "/ui/style/~a" (%path-segment (first each))))))
      (setf (fs:contents n) (second each))
      (setf (fs:owner n) fs:*owner*)))
  (styles))

(defun built-in ()
  (flet ((p (role) (css-color role)) (mono () (css-mono)))
    (list
     (list "*" (list :border-width "0" :border-style "none" :box-shadow "none"
                     :background-color "transparent" :background-image "none"))
     (list ".window" (list :font-family (mono) :font-size "13px" :color (p :fg)))
     (list ".cand" (list :color (p :fg)))
     (list ".cand-annot" (list :color (p :fg-dim)))
     (list ".cand-row" (list :background-color (p :bg-completion)))
     (list ".cand-row.sel" (list :background-color (p :bg-active)))
     (list ".cand-row.sel .cand" (list :color (p :accent-fg)))
     (list ".cand-row.sel .cand-annot" (list :color (p :accent-fg)))
     (list ".dbg-switch" (list :color (p :blue-faint)))
     (list ".dbg-header" (list :color (p :cyan-warmer) :font-weight "bold"))
     (list ".dbg-cond" (list :color (p :red-faint)))
     (list ".dbg-note" (list :color (p :blue-faint)))
     (list ".restart-lbl" (list :color (p :yellow-cooler)))
     (list ".restart.sel" (list :background-color (p :bg-active)))
     (list ".restart.sel .restart-lbl" (list :color (p :accent-fg)))
     (list ".dbg-bt" (list :color (p :blue-faint)))
     (list ".eval-result" (list :color (p :green-cooler) :font-weight "bold"))
     (list ".job-row.sel" (list :background-color (p :bg-active)))
     (list ".help-head" (list :color (p :cyan-warmer) :font-weight "bold"))
     (list ".help-entry" (list :color (p :fg)))
     (list ".field" (list :color (p :fg) :background-color (p :bg-alt)
                          :padding "0 4px"))
     (list ".editor" (list :background-color (p :bg) :color (p :fg)
                           :font-family (mono)))
     (list ".editor-view" (list :background-color (p :bg) :color (p :fg)))
     (list ".modeline" (list :background-color (p :accent) :color (p :accent-fg)))
     (list ".echo" (list :background-color (p :bg) :color (p :fg)))
     (list ".candidates" (list :background-color (p :bg-completion)
                               :color (p :fg))))))

(defmethod fs:works ((s sheet))
  (let ((cascade (append (built-in) (styles))))
    (setf (compiled s) (%compiled cascade))
    cascade))

(fs:mount (lambda () (make-instance 'fs:mount :describes "the look, and the surfaces"))
          "/ui")
(fs:mount (lambda () (make-instance 'fs:mount :describes "every theme there is, and which is on"))
          "/ui/theme")
(fs:mount (lambda () (make-instance 'fs:value :held +theme+)) "/ui/theme/active")
(fs:mount (lambda () (make-instance 'face-dir :describes "every face in force; write one to change it"))
          "/ui/face")
(fs:mount (lambda () (make-instance 'sheet :describes "the stylesheet, in cascade order"))
          "/ui/sheet")
(fs:mount (lambda () (make-instance 'fs:mount :describes "the rules, by selector"))
          "/ui/style")
(fs:mount (lambda () (make-instance 'fs:mount :describes "every surface, and where it goes"))
          "/ui/surface")
