(defpackage #:pine/repl/shell
  (:use #:cl)
  (:local-nicknames (#:node #:pine/fs/node) (#:tree #:pine/fs/tree)
                    (#:mount #:pine/fs/mount) (#:world #:pine/world/world)
                    (#:store #:pine/world/store) (#:cmd #:pine/repl/command)
                    (#:mode #:pine/repl/mode) (#:session #:pine/repl/session)
                    (#:process #:pine/proc/process) (#:super #:pine/proc/supervisor)
                    (#:task #:pine/run/task))
  (:export #:install #:here #:resolve #:commands-node #:command-node
           #:*supervisor* #:*store*))
(in-package #:pine/repl/shell)

(defvar *supervisor* nil)
(defvar *store* nil)

(defun supervisor () *supervisor*)
(defun store-of () *store*)

(defclass commands-node (node:node) ())
(defclass command-node (node:node)
  ((command :initarg :command :reader command)))

(defmethod node:nodes ((n commands-node))
  (loop :for c :in (cmd:commands)
        :collect (make-instance 'command-node :name (cmd:name c)
                                              :parent n :command c)))

(defmethod node:resolve ((n commands-node) name)
  (let ((c (cmd:command-named name)))
    (when c (make-instance 'command-node :name name :parent n :command c))))

(defmethod node:contents ((n commands-node)) (mapcar #'cmd:name (cmd:commands)))
(defmethod node:contents ((n command-node)) (cmd:describes (command n)))
(defmethod node:leafp ((n command-node)) t)
(defmethod node:persistp ((n commands-node)) nil)
(defmethod node:persistp ((n command-node)) nil)

(defun here (&optional (s session:*session*))
  (or (and s (session:node-of s)) (world:root world:*world*)))

(defun resolve (s where)
  (cond ((null where) (here s))
        ((node:nodep where) where)
        ((and (stringp where) (plusp (length where)) (char= #\/ (char where 0)))
         (tree:at (world:root world:*world*) where))
        (t (tree:at (here s) (princ-to-string where)))))

(defun install ()
  (cmd:defcommand "pwd" () (:describes "where this session is")
    (node:full-name (here)))
  (cmd:defcommand "ls" (&optional where) (:describes "what is under a node")
    (let ((n (resolve session:*session* where)))
      (if n (tree:listing n) (list))))
  (cmd:defcommand "cd" (&optional where) (:describes "go to a node")
    (let ((n (if where (resolve session:*session* where)
                 (world:root world:*world*))))
      (when (and n session:*session*)
        (setf (session:node-of session:*session*) n))
      (and n (node:full-name n))))
  (cmd:defcommand "cat" (where) (:describes "what a node holds")
    (let ((n (resolve session:*session* where)))
      (and n (node:contents n))))
  (cmd:defcommand "put" (where value) (:describes "write a node")
    (let ((n (tree:ensure (if (and (stringp where) (plusp (length where))
                                   (char= #\/ (char where 0)))
                              (world:root world:*world*)
                              (here))
                          (princ-to-string where))))
      (setf (node:contents n) value)))
  (cmd:defcommand "mkdir" (where) (:describes "make a node")
    (node:full-name (tree:ensure (here) (princ-to-string where))))
  (cmd:defcommand "rm" (where) (:describes "take a node off")
    (and (tree:erase (here) (princ-to-string where)) t))
  (cmd:defcommand "mount" (where name) (:describes "put a real directory in the tree")
    (node:full-name (mount:mount where (world:root world:*world*)
                                 (princ-to-string name))))
  (cmd:defcommand "tree" (&optional where) (:describes "every node under one")
    (tree:names (resolve session:*session* where)))
  (cmd:defcommand "live" () (:describes "what answers from the world, not the store")
    (let (acc)
      (tree:walk (world:root world:*world*)
                 (lambda (n) (when (node:livep n) (push (node:full-name n) acc))))
      (nreverse acc)))
  (cmd:defcommand "ps" () (:describes "what is running")
    (loop :for p :in (super:processes (supervisor))
          :collect (list (process:name p) (process:state p)
                         (process:attempts p))))
  (cmd:defcommand "spawn" (name argv) (:describes "run a program under the supervisor")
    (let ((p (make-instance 'process:program :name (princ-to-string name)
                                             :argv (list "sh" "-c" argv))))
      (super:supervise (supervisor) p)
      (process:start p)
      (process:name p)))
  (cmd:defcommand "kill" (name) (:describes "stop and forget a process")
    (and (super:forget (supervisor) (princ-to-string name)) t))
  (cmd:defcommand "snapshot" () (:describes "write the world to its store")
    (and (store-of) (store:snapshot world:*world* (store-of))))
  (cmd:defcommand "help" (&optional name) (:describes "what a command is for")
    (if name
        (let ((c (cmd:command-named (princ-to-string name))))
          (and c (cmd:describes c)))
        (loop :for c :in (cmd:commands)
              :collect (list (cmd:name c) (cmd:describes c)))))
  (cmd:defcommand "modes" () (:describes "every mode there is")
    (mapcar #'mode:name (mode:modes)))
  (cmd:defcommand "metrics" () (:describes "how long what pine does is taking")
    (pine/run/meter:said))
  (cmd:defcommand "metrics-reset" ()
      (:describes "start a fresh window of samples")
    (pine/run/meter:reset)
    :reset)
  (cmd:defcommand "metrics-save" (&optional where)
      (:describes "write what this daemon is doing, to lay beside a workload")
    (let ((file (or where (merge-pathnames "pine/metrics.lisp-data"
                                           (uiop:xdg-cache-home)))))
      (ensure-directories-exist file)
      (with-open-file (out file :direction :output :if-exists :supersede)
        (write (list :workload "live" :size nil :for nil
                     :image (lisp-implementation-version)
                     :seconds nil :rows (pine/run/meter:said))
               :stream out))
      (namestring file)))
  (cmd:defcommand "tasks" () (:describes "every task in this image")
    (loop :for tk :in (task:tasks)
          :collect (list (task:name tk) (task:alivep tk)))))

