(defpackage #:pine
  (:use #:cl)
  (:shadow #:describe)
  (:local-nicknames (#:node #:pine.fs.node) (#:tree #:pine.fs.tree)
                    (#:mount #:pine.fs.mount) (#:computed #:pine.fs.computed)
                    (#:world #:pine.world.world) (#:store #:pine.world.store)
                    (#:cmd #:pine.repl.command) (#:mode #:pine.repl.mode)
                    (#:session #:pine.repl.session)
                    (#:process #:pine.proc.process)
                    (#:super #:pine.proc.supervisor)
                    (#:task #:pine.run.task) (#:ui #:pine.ui.paths)
                    (#:buffer #:pine.edit.buffer) (#:window #:pine.edit.window)
                    (#:edit #:pine.edit.commands) (#:key #:pine.edit.key)
                    (#:render #:pine.edit.render)
                    (#:net #:pine.net.server) (#:attach #:pine.net.attach)
                    (#:agent #:pine.net.agent) (#:plisp #:pine.proc.lisp)
                    (#:sh #:pine.provider.sh) (#:env #:pine.provider.env)
                    (#:clock #:pine.provider.clock) (#:sys #:pine.provider.sys)
                    (#:term #:pine.edit.term) (#:fault #:pine.run.fault))
  (:export #:start #:stop #:main #:*supervisor* #:*store* #:*image* #:here
           #:describe #:commands-node #:command-node #:frame #:type!
           #:daemon #:spawn-agent #:run-app #:load-config #:config-file
           #:frontend #:declare-frontends #:+frontends+))

(in-package #:pine)

(defvar *supervisor* nil)
(defvar *store* nil)
(defvar *image* nil)

(defparameter +frontends+ '("editor" "desktop"))

(defclass commands-node (node:node) ())
(defclass command-node (node:node)
  ((command :initarg :command :reader command)))

(defmethod node:nodes ((n commands-node))
  (loop :for c :in (cmd:commands)
        :collect (make-instance 'command-node :name (cmd:name c)
                                              :parent n :command c)))

(defmethod node:resolve ((n commands-node) name)
  (let ((c (cmd:command-named name)))
    (when c (make-instance 'command-node :name name :parent n :command c))))

(defmethod node:contents ((n commands-node)) (mapcar #'cmd:name (cmd:commands)))
(defmethod node:contents ((n command-node)) (cmd:describes (command n)))
(defmethod node:leafp ((n command-node)) t)
(defmethod node:persistp ((n commands-node)) nil)
(defmethod node:persistp ((n command-node)) nil)

(defun here (&optional (s session:*session*))
  (or (and s (session:node-of s)) (world:root world:*world*)))

(defun %resolve (s where)
  (cond ((null where) (here s))
        ((node:nodep where) where)
        ((and (stringp where) (plusp (length where)) (char= #\/ (char where 0)))
         (tree:at (world:root world:*world*) where))
        (t (tree:at (here s) (princ-to-string where)))))

(defun %seed-commands ()
  (cmd:defcommand "pwd" () (:describes "where this session is")
    (node:full-name (here)))
  (cmd:defcommand "ls" (&optional where) (:describes "what is under a node")
    (let ((n (%resolve session:*session* where)))
      (if n (tree:listing n) (list))))
  (cmd:defcommand "cd" (&optional where) (:describes "go to a node")
    (let ((n (if where (%resolve session:*session* where)
                 (world:root world:*world*))))
      (when (and n session:*session*)
        (setf (session:node-of session:*session*) n))
      (and n (node:full-name n))))
  (cmd:defcommand "cat" (where) (:describes "what a node holds")
    (let ((n (%resolve session:*session* where)))
      (and n (node:contents n))))
  (cmd:defcommand "put" (where value) (:describes "write a node")
    (let ((n (tree:ensure (if (and (stringp where) (plusp (length where))
                                   (char= #\/ (char where 0)))
                              (world:root world:*world*)
                              (here))
                          (princ-to-string where))))
      (setf (node:contents n) value)))
  (cmd:defcommand "mkdir" (where) (:describes "make a node")
    (node:full-name (tree:ensure (here) (princ-to-string where))))
  (cmd:defcommand "rm" (where) (:describes "take a node off")
    (and (tree:erase (here) (princ-to-string where)) t))
  (cmd:defcommand "mount" (where name) (:describes "put a real directory in the tree")
    (node:full-name (mount:mount where (world:root world:*world*)
                                 (princ-to-string name))))
  (cmd:defcommand "tree" (&optional where) (:describes "every node under one")
    (tree:names (%resolve session:*session* where)))
  (cmd:defcommand "live" () (:describes "what answers from the world, not the store")
    (let (acc)
      (tree:walk (world:root world:*world*)
                 (lambda (n) (when (node:livep n) (push (node:full-name n) acc))))
      (nreverse acc)))
  (cmd:defcommand "ps" () (:describes "what is running")
    (loop :for p :in (super:processes *supervisor*)
          :collect (list (process:name p) (process:state p)
                         (process:attempts p))))
  (cmd:defcommand "spawn" (name argv) (:describes "run a program under the supervisor")
    (let ((p (make-instance 'process:program :name (princ-to-string name)
                                             :argv (list "sh" "-c" argv))))
      (super:supervise *supervisor* p)
      (process:start p)
      (process:name p)))
  (cmd:defcommand "kill" (name) (:describes "stop and forget a process")
    (and (super:forget *supervisor* (princ-to-string name)) t))
  (cmd:defcommand "snapshot" () (:describes "write the world to its store")
    (and *store* (store:snapshot world:*world* *store*)))
  (cmd:defcommand "help" (&optional name) (:describes "what a command is for")
    (if name
        (let ((c (cmd:command-named (princ-to-string name))))
          (and c (cmd:describes c)))
        (loop :for c :in (cmd:commands)
              :collect (list (cmd:name c) (cmd:describes c)))))
  (cmd:defcommand "modes" () (:describes "every mode there is")
    (mapcar #'mode:name (mode:modes)))
  (cmd:defcommand "tasks" () (:describes "every task in this image")
    (loop :for tk :in (task:tasks)
          :collect (list (task:name tk) (task:alivep tk)))))

(defun %seed-modes ()
  (mode:mode "text" :settings '(:tab-width 8 :indicator "Text"))
  (mode:mode "prog" :parent "text" :settings '(:indent 2 :comment ";"))
  (mode:mode "lisp" :parent "prog" :settings '(:indicator "Lisp")
                    :claims '((:files "*.lisp" "*.asd" "*.cl")))
  (mode:mode "shell" :settings '(:indicator "Shell")))

(defun start (&key (name "pine") store remoting)
  (setf world:*world* (world:make-world :name name)
        *supervisor* (super:supervisor))
  (when remoting
    (setf *image* (net:start-server :remoting-port remoting)
          net:*server* *image*)
    (attach:listen-for-attach *image*)
    (agent:listen-for-agents *image*))
  (node:attach (make-instance 'commands-node :name "cmd"
                                             :describes "every command there is")
               (world:root world:*world*))
  (world:ensure world:*world* "buf")
  (world:ensure world:*world* "win")
  (%seed-commands)
  (%seed-modes)
  (ui:install world:*world*)
  (let ((root (world:root world:*world*)))
    (sh:install root)
    (env:install root)
    (sys:install root)
    (clock:install root :supervisor *supervisor*)
    (mount:mount "/" root "file"))
  (edit:install)
  (term:install)
  (let ((scratch (buffer:make-buffer "scratch" :mode "lisp")))
    (setf (buffer:current) scratch)
    (window:seed! scratch))
  (when store
    (setf *store* (store:open-store store))
    (store:restore world:*world* *store*))
  (super:watch *supervisor*)
  world:*world*)

(defun stop ()
  (when *supervisor*
    (super:unwatch *supervisor*)
    (super:stop-all *supervisor*))
  (dolist (s (session:sessions)) (session:close s))
  (when *store*
    (ignore-errors (store:snapshot world:*world* *store*))
    (ignore-errors (store:close-store *store*))
    (setf *store* nil))
  (dolist (tk (task:tasks)) (task:stop tk))
  (when *image*
    (ignore-errors (net:stop-server *image*))
    (setf *image* nil net:*server* nil))
  t)

(defun main (&key store)
  (start :store store)
  (let ((s (session:open-session :name "console" :mode "shell"
                                 :node (world:root world:*world*)
                                 :package (find-package :pine))))
    (unwind-protect (session:interact s)
      (stop))))

(defun type! (text &optional (session session:*session*))
  (declare (ignore session))
  (loop :for ch :across text
        :do (key:dispatch nil (key:make-key (string ch))))
  (buffer:point (buffer:current)))

(defun frame (&key (width 80) (height 24))
  (mapcar #'car (render:rows :width width :height height)))

(defun config-file ()
  (merge-pathnames "pine/init.lisp" (uiop:xdg-config-home)))

(defun load-config (&optional (file (config-file)))
  (when (and file (probe-file file))
    (let ((*package* (find-package :pine)))
      (fault:attempt (lambda () (load file)) (format nil "loading ~a" file)))))

(defun %frontend-command (verb)
  (let ((self (first sb-ext:*posix-argv*)))
    (if (and self (not (search "sbcl" (namestring self))))
        (list self verb)
        (list (namestring sb-ext:*runtime-pathname*)
              "--noinform" "--no-userinit" "--non-interactive"
              "--eval" "(require :asdf)"
              "--eval" "(asdf:load-system :pine/wayland)"
              "--eval" (format nil "(pine:run-app ~s)" verb)))))

(defun %frontend-environment ()
  (cons (format nil "PINE_PORT=~d" net:*port*)
        (remove-if (lambda (entry)
                     (and (>= (length entry) 10)
                          (string= "PINE_PORT=" entry :end2 10)))
                   (sb-ext:posix-environ))))

(defun frontend (verb)
  (make-instance 'process:program
                 :name verb
                 :argv (%frontend-command verb)
                 :env (%frontend-environment)))

(defun declare-frontends (&optional (which +frontends+))
  (dolist (verb which)
    (unless (super:process-named *supervisor* verb)
      (let ((p (frontend verb)))
        (super:supervise *supervisor* p)
        (setf (node:contents (world:ensure world:*world* "proc" verb)) :declared)
        (fault:attempt (lambda () (process:start p))
                       (format nil "starting the ~a frontend" verb)))))
  (mapcar #'process:name (super:processes *supervisor*)))

(defun daemon (&key store (remoting net:*port*) (config (config-file)))
  (start :store store :remoting remoting)
  (cmd:defcommand "agents" () (:describes "every image attached to this one")
    (mapcar #'agent:name (agent:agents)))
  (cmd:defcommand "clients" () (:describes "every frontend attached")
    (loop :for c :in (attach:clients)
          :collect (list (attach:client-kind c) (attach:client-id c))))
  (load-config config)
  *image*)

(defun spawn-agent (name)
  (let ((p (make-instance 'plisp:lisp-process :name name :systems '(:pine))))
    (super:supervise *supervisor* p)
    (process:start p)
    p))

(defun run-app (verb)
  (net:read-environment)
  (attach:run-frontend (intern (string-upcase verb) :keyword)))

(defun describe (where)
  (let ((n (%resolve nil where)))
    (when n
      (list :name (node:full-name n)
            :class (class-name (class-of n))
            :describes (node:describe n)
            :under (tree:listing n)
            :persists (node:persistp n)))))
