(defpackage #:pine
  (:use #:cl)
  (:shadow #:describe)
  (:local-nicknames (#:build #:pine/ui/build) (#:data #:pine/data)
                    (#:node #:pine/fs/node) (#:tree #:pine/fs/tree)
                    (#:mount #:pine/fs/mount) (#:watch #:pine/fs/watch)
                    (#:world #:pine/world/world) (#:store #:pine/world/store)
                    (#:cmd #:pine/repl/command) (#:mode #:pine/repl/mode)
                    (#:session #:pine/repl/session) (#:shell #:pine/repl/shell)
                    (#:process #:pine/proc/process)
                    (#:supervisor #:pine/proc/supervisor)
                    (#:lisp-process #:pine/proc/lisp)
                    (#:task #:pine/run/task) (#:timer #:pine/run/timer)
                    (#:endpoint #:pine/run/agent) (#:fault #:pine/run/fault)
                    (#:libs #:pine/run/libs) (#:log #:pine/run/log)
                    (#:place #:pine/path/place)
                    (#:ui #:pine/ui/paths) (#:css #:pine/ui/css)
                    (#:runtime #:pine/ts/runtime) (#:syntax #:pine/ts/syntax)
                    (#:parser #:pine/ts/parser)
                    (#:sh #:pine/provider/sh) (#:env #:pine/provider/env)
                    (#:clock #:pine/provider/clock) (#:sys #:pine/provider/sys)
                    (#:audio #:pine/provider/audio) (#:screen #:pine/provider/screen)
                    (#:power #:pine/provider/power) (#:network #:pine/provider/net)
                    (#:media #:pine/provider/media) (#:wm #:pine/provider/wm)
                    (#:live #:pine/provider/live)
                    (#:buffer #:pine.edit.buffer) (#:window #:pine.edit.window)
                    (#:defaults #:pine.edit.defaults) (#:key #:pine.edit.key)
                    (#:render #:pine.edit.render) (#:term #:pine.edit.term)
                    (#:motion #:pine.edit.motion) (#:listing #:pine.edit.listing)
                    (#:isearch #:pine.edit.isearch) (#:evaluate #:pine.edit.eval)
                    (#:repl-buffer #:pine.edit.repl)
                    (#:debugger #:pine.edit.debugger)
                    (#:editor #:pine.edit.session)
                    (#:net #:pine.net.server) (#:attach #:pine.net.attach)
                    (#:control #:pine.net.control) (#:agent #:pine.net.agent)
                    (#:desktop #:pine.app.desktop) (#:wm-app #:pine.app.wm)
                    (#:compositor #:pine.app.compositor))
  (:export #:start #:stop #:main #:*supervisor* #:*store* #:*image* #:here
           #:describe #:frame #:type!
           #:daemon #:quit #:spawn-agent #:run-app #:load-config #:config-file
           #:user-package #:write-at #:read-at
           #:audio #:screen #:power #:network #:media #:procfs #:shell #:niri
           #:compositor #:style
           #:frontend #:declare-frontends #:+frontends+))
(in-package #:pine)

(defvar *supervisor* nil)

(defvar *store* nil)

(defvar *image* nil)

(defparameter +frontends+ '("editor" "desktop"))

(defparameter +user-surface+
  '((:pine "declare-frontends" "frontend" "start" "stop" "here" "spawn-agent"
     "audio" "screen" "power" "network" "media" "procfs" "shell" "niri" "compositor"
     "style")
    (:pine/repl/command "defcommand" "command" "command-named" "commands" "run")
    (:pine/repl/mode "mode" "minor" "bind" "handle" "setting" "modes")
    (:pine/fs/node "contents" "nodes" "name" "attach" "describes")
    (:pine/fs/tree "at" "ensure" "place" "erase" "listing")
    (:pine/world/world "*world*" "root")
    (:pine.app.surface "surface" "defsurface" "show!" "hide!" "toggle!" "surfaces")
    (:pine.edit.render "frame-tree")
    (:pine/ui/face "color" "metric")
    (:pine/ui/css "css-glass" "css-rad" "css-mono")
    (:pine/path/path "leaf")
    (:pine/ui/build "column" "row" "label" "icon" "button" "box" "center"
     "scroll" "gap" "rule" "slider" "grid" "stack" "field" "rows" "choice"
     "calendar" "image" "centerbox" "ring" "cells" "here" "acting")
    (:pine/fs/node "stir" "child")
    (:pine.edit.prompt "ask")
    (:pine/run/log "note")
    (:pine/data "map" "seq" "set")))

(defun start (&key (name "pine") store remoting)
  (flet ((seed-modes ()
           (mode:mode "text" :settings '(:tab-width 8 :indicator "Text"))
           (mode:mode "prog" :parent "text" :settings '(:indent 2 :comment ";"))
           (mode:mode "lisp" :parent "prog" :settings '(:indicator "Lisp")
                             :claims '((:files "*.lisp" "*.asd" "*.cl")))
           (mode:mode "shell" :settings '(:indicator "Shell")))
         (seed-syntax ()
           (let ((runtime (runtime:make-ts-runtime)))
             (fault:attempt (lambda () (runtime:ensure-ts runtime))
                            "loading tree-sitter")
             (when (runtime:ts-loaded-p runtime)
               (setf parser:*runtime* runtime)
               (syntax:install world:*world*)))))
  (libs:attend)
  (setf world:*world* (world:make-world :name name)
        *supervisor* (supervisor:supervisor)
        *image* (net:start-server :remoting-port remoting)
        net:*server* *image*)
  (timer:attend (net:actor-system *image*))
  (endpoint:attend (net:actor-system *image*))
  (when remoting
    (attach:listen-for-attach *image*)
    (agent:listen-for-agents *image*))
  (node:attach (make-instance 'shell:commands-node :name "cmd"
                                                   :describes "every command there is")
               (world:root world:*world*))
  (world:ensure world:*world* "buf")
  (world:ensure world:*world* "win")
  (setf shell:*supervisor* *supervisor* shell:*store* *store*)
  (shell:install)
  (seed-modes)
  (ui:install world:*world*)
  (let ((root (world:root world:*world*)))
    (sh:install root)
    (env:install root)
    (sys:install root)
    (clock:install root :supervisor *supervisor*)
    (mount:mount "/" root "file"))
  (defaults:install)
  (motion:install)
  (listing:install)
  (isearch:install)
  (repl-buffer:install)
  (debugger:install)
  (evaluate:install)
  (desktop:install)
  (wm-app:install)
  (compositor:install)
  (term:install)
  (editor:install)
  (seed-syntax)
  (let ((scratch (buffer:make-buffer "scratch" :mode "lisp")))
    (setf (buffer:current) scratch)
    (window:seed! scratch))
  (when store
    (setf *store* (store:open-store store))
    (setf shell:*store* *store*)
    (store:restore world:*world* *store*)
    (store:keeping *store*))
  (supervisor:watch *supervisor*)
  (timer:every-seconds 5 (lambda () (attach:sweep *image*))
                       :as :reap :what "sweeping dead clients")
  world:*world*))

(defun stop ()
  (setf cmd:*asking* nil
        build:*asking* nil
        build:*editing* nil
        network:*asking* nil)
  (key:take-next nil)
  (isearch:took-all)
  (live:leave-all)
  (parser:forget-all)
  (watch:forget-all)
  (when *supervisor*
    (supervisor:unwatch *supervisor*)
    (supervisor:stop-all *supervisor*))
  (dolist (s (session:sessions)) (session:close s))
  (dolist (c (copy-list (attach:clients))) (attach:reap c *image*))
  (editor:close-all)
  (desktop:close-all)
  (setf node:*on-write* nil)
  (when *store*
    (ignore-errors (store:snapshot world:*world* *store*))
    (ignore-errors (store:close-store *store*))
    (setf *store* nil))
  (dolist (tk (task:tasks)) (task:stop tk))
  (timer:leave)
  (when *image*
    (ignore-errors (net:stop-server *image*))
    (setf *image* nil net:*server* nil))
  t)

(defun main (&key store)
  (start :store store)
  (let ((s (session:open-session :name "console" :mode "shell"
                                 :node (world:root world:*world*)
                                 :package (find-package :pine))))
    (unwind-protect (session:interact s)
      (stop))))

(defun type! (text &optional (session session:*session*))
  (declare (ignore session))
  (loop :for ch :across text
        :do (key:dispatch nil (key:make-key (string ch))))
  (buffer:point (buffer:current)))

(defun frame (&key (width 80) (height 24))
  (mapcar #'car (render:rows :width width :height height)))

(defun procfs () (live:attend (sys:install (world:root world:*world*))))
(defun shell () (sh:install (world:root world:*world*)))
(defun audio (&optional (name "audio"))
  (live:attend (audio:install (world:root world:*world*) name)))
(defun screen (&optional (name "screen"))
  (live:attend (screen:install (world:root world:*world*) name)))
(defun power (&optional (name "power"))
  (live:attend (power:install (world:root world:*world*) name)))
(defun network (&optional (name "net"))
  (live:attend (network:install (world:root world:*world*) name)))
(defun media (&key (name "media") player)
  (live:attend (media:install (world:root world:*world*) :name name :player player)))

(defun niri (&optional (name "wm")) (live:attend (wm:install (world:root world:*world*) name)))

(defun compositor () (compositor:pine-wm world:*world*))

(defun style (selector props)
  (prog1 (first (css:install (list (list selector props))))
    (css:broadcast)))

(defun %place (where)
  (cond ((node:nodep where) where)
        ((stringp where) (tree:at (world:root world:*world*) where))
        (t where)))

(defun write-at (where value)
  (let ((it (%place where)))
    (if (node:nodep it)
        (setf (node:contents it) value)
        (setf (place:contents it) value))))

(defun read-at (where &optional default)
  (let* ((it (%place where))
         (value (if (node:nodep it) (node:contents it) (place:contents it))))
    (if (null value) default value)))

(defun user-package ()
  (or (find-package :pine.user)
      (let ((p (make-package :pine.user :use '(:cl))))
        (dolist (entry +user-surface+)
          (dolist (name (rest entry))
            (let ((symbol (find-symbol (string-upcase name) (first entry))))
              (when symbol (shadowing-import symbol p)))))
        (shadow '("WRITE" "READ") p)
        (setf (fdefinition (intern "WRITE" p)) #'write-at
              (fdefinition (intern "READ" p)) #'read-at)
        (export (list (intern "WRITE" p) (intern "READ" p)) p)
        p)))

(defun config-file ()
  (merge-pathnames "pine/init.lisp" (uiop:xdg-config-home)))

(defun load-config (&optional (file (config-file)))
  (user-package)
  (when (and file (probe-file file))
    (let ((*package* (user-package))
          (*readtable* (named-readtables:find-readtable 'pine/path/reader:syntax))
          (before (length (fault:faults))))
      (log:note "reading ~a" file)
      (fault:attempt (lambda () (load file)) (format nil "reading ~a" file))
      (let ((broke (- (length (fault:faults)) before)))
        (when (plusp broke)
          (log:note "~a did not log: ~a" file
                     (fault:condition-of (first (fault:faults)))))
        (zerop broke)))))

(defun frontend (verb)
  "The process that runs a frontend: this image again where pine is a binary,
and an sbcl told to load pine where it is not, with the port it attaches to in
its environment."
  (flet ((argv ()
           (let ((self (first sb-ext:*posix-argv*)))
             (if (and self (not (search "sbcl" (namestring self))))
                 (list self verb)
                 (list (namestring sb-ext:*runtime-pathname*)
                       "--noinform" "--no-userinit" "--non-interactive"
                       "--eval" "(require :asdf)"
                       "--eval" "(asdf:load-system :pine/wayland)"
                       "--eval" (format nil "(pine:run-app ~s)" verb)))))
         (environment ()
           (cons (format nil "PINE_PORT=~d" net:*port*)
                 (remove-if (lambda (entry)
                              (and (>= (length entry) 10)
                                   (string= "PINE_PORT=" entry :end2 10)))
                            (sb-ext:posix-environ)))))
    (make-instance 'process:program :name verb
                                    :argv (argv) :env (environment))))

(defun declare-frontends (&optional (which +frontends+))
  (dolist (verb which)
    (unless (or (supervisor:process-named *supervisor* verb)
                (attach:attached-p (intern (string-upcase verb) :keyword)))
      (let ((p (frontend verb)))
        (supervisor:supervise *supervisor* p)
        (setf (node:contents (world:ensure world:*world* "proc" verb)) :declared)
        (fault:attempt (lambda () (process:start p))
                       (format nil "starting the ~a frontend" verb)))))
  (mapcar #'process:name (supervisor:processes *supervisor*)))

(defun quit (&optional (grace 5))
  (task:spawn "quit-watchdog"
              (lambda () (sleep grace) (sb-ext:exit :abort t :code 0)))
  (task:spawn "quit"
              (lambda ()
                (sleep 0.2)
                (ignore-errors (stop))
                (sb-ext:exit :abort t :code 0)))
  t)

(defun daemon (&key store (remoting net:*port*) (config (config-file)))
  (start :store store :remoting remoting)
  (cmd:defcommand "agents" () (:describes "every image attached to this one")
    (mapcar #'agent:name (agent:agents)))
  (cmd:defcommand "clients" () (:describes "every frontend attached")
    (loop :for c :in (attach:clients)
          :collect (list (attach:client-kind c) (attach:client-id c))))
  (setf control:*on-reload* (lambda () (load-config config) :reloaded)
        control:*agents* (lambda () (mapcar #'agent:name (agent:agents))))
  (control:serve *image* :on-quit #'quit)
  (load-config config)
  (log:note "~a: remoting ~d, ~d command~:p, ~d running"
             (world:name world:*world*)
             (net:remoting-port *image*)
             (length (cmd:commands))
             (length (supervisor:processes *supervisor*)))
  *image*)

(defun spawn-agent (name)
  (let ((p (make-instance 'lisp-process:lisp-process :name name :systems '(:pine))))
    (supervisor:supervise *supervisor* p)
    (process:start p)
    p))

(defun run-app (verb)
  (net:read-environment)
  (attach:run-frontend (intern (string-upcase verb) :keyword)))

(defun describe (where)
  (let ((n (shell:resolve nil where)))
    (when n
      (list :name (node:full-name n)
            :class (class-name (class-of n))
            :describes (node:describe n)
            :under (tree:listing n)
            :persists (node:persistp n)))))
